### ISSUE TITLE
Microk8s traefik

### ISSUE THREAD

**Issue by JElgar** [canonical/microk8s#1851]
This is probably a Q+A rather than a bug. I'm having a go at using microk8s traefik addon.

Looking at the spec it seems the dashboard should be enabled at '/'. Once enable if I go to the ip of the server I get a traefik 404 page. Similarly, if I run 
kubectl port-forward -n traefik service/traefik-web-ui 1080:8080
and try and access the dashboard through 127.0.0.1:1080/ I also get the traefik 404

This is probably a very dumb question but any help would be greatly appreciated.

Another question that may be the source of a lot more of my confusion, why is port 8080 used and not port 80? If I add an ingress with host traefik.example.com and path '/' and then go to traefik.example.com/ I will get nothing whereas with traefik.example.com:8080/ I get the traefik 404.

[inspection-report-20201228_111603.tar.gz](https://github.com/ubuntu/microk8s/files/5746905/inspection-report-20201228_111603.tar.gz)

**Comment by balchua** [comment]
@JElgar the service name isn't `traefik-web-ui`.  It is `traefik-ingress-service` instead.

Can you try `kubectl -n traefik port-forward svc/traefik-ingress-service 1080:8080`?

**Comment by mikedmor** [comment]
I also seem to be experiencing the same issues. Port 8080 returns "404 page not found", the problem was not solved with the above command. 

I'm new to Kubernetes and microk8s so I may have done something wrong, but so far this is all I have done:

1.) Install Ubuntu Server ARM64 on RPI V4
2.) `sudo usermod -a -G microk8s <username>` - add user to microk8s group
3.) Restart to apply new user group
4.) `snap install microk8s --classic`
5.) `apt-get update -qq` & `apt-get install -qq -y iptables-persistent` & `iptables -P FORWARD ACCEPT`
6.) `microk8s enable dashboard dns host-access portainer registry storage traefik`
7.) `snap alias microk8s.kubectl kubectl`
8.) Generate Token and then `sudo microk8s dashboard-proxy`
9.) Log into Kubernetes Dashboard - Working
10.) Attempt to access Traefik on Port 8080 - Returns "404 page not found"
11.) `kubectl port-forward -n traefik service/traefik-web-ui 1080:8080`
12.) Attempt to access Traefik on Port 8080 again - Still Returns "404 page not found"

Let me know if there is any more information that I can provide to help.

**Comment by balchua** [comment]
How about accessong the page with `http://localhost:1080/dasboard/`
Im looking at this docs.

https://doc.traefik.io/traefik/operations/dashboard/#insecure-mode

Do you see `traefik-web-ui` service resource in `traefik` namespace?

**Comment by mikedmor** [comment]
Using port 1080 shows "This site can't be reached", if run step 11 from my previous message however, I see "404 page not found".

Checking out the traefik namespace I do see the traefik-web-ui under "Ingress", under Applications in this resource pool it only shows "traefik-ingress-controller".

**Comment by lazyoldbear** [comment]
Looks like this is the reason (traefik pod log): 
`E0107 05:32:27.518090       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1beta1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:traefik:traefik-ingress-controller" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope`

**Comment by balasu** [comment]
Hi microk8s enable traefik is just an ingress controller, on top of it user can change as per his requirement.
for dashboard to work, pl edit daemonset file and add 
- --api.insecure=true
- --api.dashboard=true
also change entrypoint port as per requirement. however its not secured

**Comment by HtheChemist** [comment]
You also need to change the web entrypoint to something else than :8080 since the dashboard will bind this port and create problem.

Here is an example that work:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: default
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: default
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik:2.3
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --providers.kubernetesingress=true
        - --providers.kubernetesingress.ingressendpoint.ip=127.0.0.1
        - --api.dashboard=true
        - --api.insecure=true
        - --log=true
        - --log.level=INFO
        - --accesslog=true
        - --accesslog.filepath=/dev/stdout
        - --accesslog.format=json
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:8443
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: default
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      name: admin
---
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: default
spec:
  rules:
  - host: <your host>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-web-ui
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80
```

**Comment by balchua** [comment]
Thanks guys for these info.  @balasu do you think it will be good to have option to enable the traefik dashboard when enabling the traefik addon?

Thanks!

**Comment by balasu** [comment]
Hi @balchua , it depends on the usecase, microk8s enable traefik is just an ingress controller for underlying cluster. if there is a requirement, traefik ingress controller has to be installed as CRD where its secured.
https://doc.traefik.io/traefik/user-guides/crd-acme/

**Comment by balchua** [comment]
Im no traefik guru, but providing option to enable the traefik dashboard will provide better UX.
Wdyt?

**Comment by balasu** [comment]
yes, let me check with traefik team as well. however i think we should move to CRD based implementation for a better secured deployment rather than exposing the UI on insecured way

**Comment by vrsarin** [comment]
Is there any update on this feature?

**Comment by balasu** [comment]
Hi @vrsarin Sorry for the delayed reply, Traefik CRD implementation currently parked as many changes are going thru. Incase there is a requirement to use UI, users can use portainer dashboard to management the cluster and deploy applications

**Comment by cz3pa** [comment]
Hello, for me it was missing docker installation... After docker installation traefik dashboard appeared (no 404 😃 ).

**Comment by jwtodd** [comment]
thx for the patch @HtheChemist. i can now access the traefik-dashboard. that said, i'm unable to add a new ingress-route, event the above provided whoami ingress example fails for me.

thoughts?

microk8s:2.2.0
traefik enabled

a curl .../whoami logs the following, noting the routerName is 'dashboard@internal' ... not the route i registered per the [above patch](https://github.com/ubuntu/microk8s/issues/1851#issuecomment-757523767) while changing the whoami pathPrefix to '/whoami':

{"ClientAddr":"192.168.64.1:59948","ClientHost":"192.168.64.1","ClientPort":"59948","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":175694,"OriginContentSize":19,"OriginDuration":116763,"OriginStatus":404,"Overhead":58931,"RequestAddr":"192.168.64.5:8080","RequestContentSize":0,"RequestCount":181,"RequestHost":"192.168.64.5","RequestMethod":"GET","RequestPath":"/whoami","RequestPort":"8080","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"dashboard@internal","StartLocal":"2021-11-30T07:09:54.913197696Z","StartUTC":"2021-11-30T07:09:54.913197696Z","entryPointName":"traefik","level":"info","msg":"","time":"2021-11-30T07:09:54Z"}

**Comment by HtheChemist** [comment]
@jwtodd: it seems that you request the port 8080, have you tried with port 80?

**Comment by jwtodd** [comment]
the multipass host, osx, endpoint is on 8080 which does resolve to the dashboard via the 'dasboard@internal' route.

just not sure how to add additional application routes.

traefik worked for us under docker-desktop with  traefik.containo.us/v1alpha1:IntegressRoute defs.

**Comment by HtheChemist** [comment]
In your Traefik ingress Deamonset, change the entrypoint to the following:
```
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:8443
```

The /whoami container should be also changed to :80 (for example in a:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
```

And then add a service on port 80 for whoami.:
```
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
```

Note that this port can be any port EXCEPT the same port as the dashboard. I am unsure why

In my local deployment, my ingress are the following:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: local-ingress
  namespace: local
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: django
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /dashboard/
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 8080
```

Since it work for my use I have not investigated further. If you insist on using port 8080 you can probably add an ingress with a path of `/` that also point to traefik.
