### ISSUE TITLE
Ingress add-on not working in v1.20.0 (1864)

### ISSUE THREAD

**Issue by autoguy14** [canonical/microk8s#1890]
I have been trying unsuccessfully to get ingress working in this release (working fine in 1.19). The ingress resource is created successfully, but there is nothing listening on the registered port on the nodes. I have now tried this with the ingress.yaml from the test suite and experience the same issue.

Steps to reproduce:

- `lsb_release -a`
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
- `snap info microk8s`
`installed:          v1.20.0             (1864) 219MB classic`
[inspection-report-20210112_095144.tar.gz](https://github.com/ubuntu/microk8s/files/5801285/inspection-report-20210112_095144.tar.gz)

- `microk8s enable dns ingress`
- `microk8s kubectl apply -f ingress.yaml` - copied from https://github.com/ubuntu/microk8s/blob/master/tests/templates/ingress.yaml (and updated $ARCH)
- `microk8s kubectl get pods`
```
NAME                        READY   STATUS    RESTARTS   AGE
microbot-569dfdf8c8-t89v8   1/1     Running   0          22m
```
- `microk8s kubectl get svc`
```
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP   3d13h
microbot     ClusterIP   10.152.183.39   <none>        80/TCP    24m
```
- `curl 10.152.183.39:80`
```
<!DOCTYPE html>
<html>
  <style type="text/css">
    .centered
      {
      text-align:center;
      margin-top:0px;
      margin-bottom:0px;
      padding:0px;
      }
  </style>
  <body>
    <p class="centered"><img src="microbot.png" alt="microbot"/></p>
    <p class="centered">Container hostname: microbot-569dfdf8c8-t89v8</p>
  </body>
</html>
```
- `microk8s kubectl get ing`
```
NAME                   CLASS    HOSTS                       ADDRESS     PORTS   AGE
microbot-ingress-xip   public   microbot.127.0.0.1.xip.io   127.0.0.1   80      26m
microbot-ingress-nip   public   microbot.127.0.0.1.nip.io   127.0.0.1   80      26m
```
- `curl microbot.127.0.0.1.xip.io:80`  times out
- `curl microbot.127.0.0.1.nip.io:80`  times out
- `lsof -i :80`
```
COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
google_ne 1314 root    7u  IPv4 28872555      0t0  TCP c2-0.internal:40058->metadata.google.internal:http (ESTABLISHED)
google_ac 1315 root    5u  IPv4 28872886      0t0  TCP c2-0.internal:40056->metadata.google.internal:http (ESTABLISHED)
google_cl 1317 root    5u  IPv4 28865968      0t0  TCP c2-0.internal:39890->metadata.google.internal:http (CLOSE_WAIT)
google_cl 1317 root    6u  IPv4 28871510      0t0  TCP c2-0.internal:40032->metadata.google.internal:http (ESTABLISHED)
```
There is nothing listening on port 80

**Comment by ktsakalozos** [comment]
I cannot spot a problem in your cluster and i am setting a single node cluster here and it works. Could you share the output of `curl -v microbot.127.0.0.1.xip.io:80` does it timeout when trying to reach the ingress or xip.io ?

**Comment by autoguy14** [comment]
Thanks for looking into this.
```
curl -v microbot.127.0.0.1.xip.io:80
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to microbot.127.0.0.1.xip.io port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to microbot.127.0.0.1.xip.io port 80: Connection refused
```
It's definitely trying to connect to 127.0.0.1:80.  I will try a fresh install on a single node and see if I get the same result

**Comment by autoguy14** [comment]
I remove microk8s and installed again on a single node. I had the same issue and could not connect to the ingress. Later for other reasons I rebooted this server and then found that the ingress was working ok. What changed on the reboot is that the snap version updated to 1.20.1 (1910). This is potentially what has fixed it. I have removed microk8s and installed again and I can create the ingress successfully. My assumption is that the version upgrade has solved my issue. Let me know however if there if any digging you would like me to do to understand this better.

**Comment by ktsakalozos** [comment]
With 1.20.1 we did this fix https://github.com/ubuntu/microk8s/pull/1832 but I though this only affects deployments with RBAC.

**Comment by raohammad** [comment]
Same problem here.. Tried with current version (default installation --channel=1.20), ingress add on behaves strange. Fallback to --channel=1.19, everything is fine.

**Comment by joeky888** [comment]
Same issue. I have found a workaround for version 1.20.

1. Make sure your 80 and 443 ports are working and are not blocked by a firewall (e.g `docker run --rm -p 80:80 nginx && curl Your_Public_IP`)
2. Run `microk8s.enable dns ingress`
3. Make sure your ingress api version is set to `apiVersion: networking.k8s.io/v1`
4. Make sure you have removed this line `kubernetes.io/ingress.class: nginx` 
5. Run `microk8s.kubectl get ingress -A` and make sure `ADDRESS` is set to `127.0.0.1` and is not empty

Example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    # kubernetes.io/ingress.class: nginx # Try to remove this line or maybe set it to "public"
    # cert-manager.io/cluster-issuer: letsencrypt-prod # This is for cert-manager
    # kubernetes.io/tls-acme: "true" # This is for cert-manager
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
```
