### ISSUE TITLE
Microk8s 1.18 Change default host path storage location

### ISSUE THREAD

**Issue by thwhk** [canonical/microk8s#1956]
Hi all, I want to use my usb drive as default storage location. I set the usb drive mount point to `/mnt/microk8s_usb`. I followed this https://github.com/ubuntu/microk8s/issues/463#issuecomment-491285745 to change `/var/snap/microk8s/current/args/containerd` as follow:
```
--config ${SNAP_DATA}/args/containerd.toml
--root /mnt/microk8s_usb/var/lib/containerd
--state /mnt/microk8s_usb/run/containerd
--address ${SNAP_COMMON}/run/containerd.sock
```

After restarted Microk8s, pods status are always `ContainerCreating`, but the node is on Ready state
When I describe the pods, it shows the following message:
```
Warning  FailedCreatePodSandBox  2m54s (x17 over 6m41s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/mnt/microk8s_usb/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/152/work upperdir=/mnt/microk8s_usb/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/152/fs lowerdir=/mnt/microk8s_usb/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1/fs]}: invalid argument: unknown
```

Am I did something wrong? Thank you.
[inspection-report-20210131_070151.tar.gz](https://github.com/ubuntu/microk8s/files/5899307/inspection-report-20210131_070151.tar.gz)

**Comment by nlnjnj** [comment]
After research the source code, I figured that currently if you want to change the deafult path you could only change the ENV `SNAP_COMMON`, but this will also move all the dirs under `SNAP_COMMON`.

If you want change the  default-storage only you could re-depoly the hostpath-provisioner

hostpath-provisioner.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-provisioner
  labels:
    k8s-app: hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: hostpath-provisioner
  template:
    metadata:
      labels:
        k8s-app: hostpath-provisioner
    spec:
      serviceAccountName: microk8s-hostpath
      containers:
        - name: hostpath-provisioner
          image: cdkbot/hostpath-provisioner-amd64:1.0.0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PV_DIR
              value: /data/default-storage
          #            - name: PV_RECLAIM_POLICY
          #              value: Retain
          volumeMounts:
            - name: pv-volume
              mountPath: /data/default-storage
      volumes:
        - name: pv-volume
          hostPath:
            path: /data/default-storage
```

Then

```bash
sudo microk8s kubectl delete -f hostpath-provisioner.yaml
sudo microk8s kubectl create -f hostpath-provisioner.yaml
```
