### ISSUE TITLE
GPU limits for pods

### ISSUE THREAD

**Issue by rockkoca** [canonical/microk8s#2160]
After enabling GPU, it seems every pod has been assigned all GPUs.

I tried the following config to limit the GPU to zero. But, it does not work. All GPUs still show up in /dev.
So, is there any way to limit the number of GPUs for a specific pod?

Thanks,
```
      resources:
        limits:
          nvidia.com/gpu: "0"
        requests:
          nvidia.com/gpu: "0"
```
