### ISSUE TITLE
how to enable kubernetes dashboard with traefik ingress route

### ISSUE THREAD

**Issue by kconde2** [canonical/microk8s#2198]
My actual ingress route

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`dashboard.<i-replaced-real-domain>.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: kubernetes-dashboard
      port: 443
  tls:
    certResolver: letsencrypt

```
Thanks in advance.
