### ISSUE TITLE
Node Exporter Failing To Start On 1.21/stable

### ISSUE THREAD

**Issue by sstubbs** [canonical/microk8s#2262]
Hi,

I'm trying `1.21/stable` in a lxd container. `1.19/stable` and `1.20/stable` work well but in `1.21/stable` the node exporter pod gives me the following error:
```
(combined from similar events): Error: failed to generate container "02f2320a5bd2ceb1b31c1cb239972b2fff85b27aa7d2d822e67ae3161eeb3a89" spec: failed to generate spec: path "/proc" is mounted on "/proc" but it is not a shared or slave mount
```

I have tried it a few times with these three versions and always get the same result.

To reproduce do the following:
```
sudo lxc profile create microk8s-dev 
wget https://raw.githubusercontent.com/ubuntu/microk8s/master/tests/lxc/microk8s.profile -O microk8s.profile
cat microk8s.profile | sudo lxc profile edit microk8s-dev
rm microk8s.profile
sudo lxc launch -p default -p microk8s-dev ubuntu:20.04 microk8s-dev
sudo lxc exec microk8s-dev -- sudo snap set system refresh.timer=sun,00:00~01:00
sudo lxc exec microk8s-dev -- sudo systemctl enable iscsid
sudo lxc exec microk8s-dev -- sudo snap install microk8s --classic --channel=1.21/stable
sudo lxc exec microk8s-dev -- microk8s enable dns rbac prometheus openebs
```

**Comment by balchua** [comment]
I got the same error here.

**Comment by sstubbs** [comment]
Hi @balchua  I just tried this again and am still getting this error.

**Comment by balchua** [comment]
@sstubbs are u still getting this error?

**Comment by balchua** [comment]
I think i found the issue.

In pre 1.21 we were using kube-prometheus 0.6.0
Which do not use `mountPropagation` on `/proc`

```
volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: false
        - mountPath: /host/sys
          name: sys
          readOnly: false
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
```
But on Microk8s v1.21+ we upgraded kube-prometheus to v0.7

Which started to use `mountPropagation`.  If you remove the mountPropagation i believe it will work.
