### ISSUE TITLE
Prometheus alerts regarding scheduler and controller-manager 

### ISSUE THREAD

**Issue by h4wkmoon** [canonical/microk8s#2379]
Hi, 

I'm running microk8s on 1 node.
microk8s           v1.20.7             2264      1.20/stable      canonical✓  classic

I'm having alerts from Prometheus on the missing KubeControllerManager and KubeScheduler.
Looking at microk8s inspect, I can see that the corresponding linux services are ok.
And I can also see that those 2 components are not static pods with kubernetes services and servicemonitor.

Is it by design ? If I'm not mistaken, being able to monitor those key components is important.
Am I missing something ?

I'm attaching a microk8s inspect report yet. I think it is not required for now. I think there is nothing wrong with my microk8s "cluster" itself.

**Comment by balchua** [comment]
@h4wkmoon i have seen this too.
My guess is to add a `Service` for the controller manager and scheduler.
But I didn't got the chance to looked into in more detail.

**Comment by h4wkmoon** [comment]
I can create a service, but without a pod to reference in the service, I don't see the point.

Am I the only one in this situation ?

**Comment by Pflegusch** [comment]
The problem is that prometheus looks for the metrics at ``0.0.0.0``, while microk8s binds the ``kube-controller-manager`` and ``kube-scheduler`` to ``127.0.0.1`` (see ``${SNAP_DATA}/args/kube-controller-manager`` resp. ``${SNAP_DATA}/args/kube-scheduler``). My guess would be to change the address to ``0.0.0.0`` and restart the underlying services with ``systemctl restart snap.microk8s.daemon-controller-manager.service`` and ``systemctl restart snap.microk8s.daemon-scheduler.service`` however, I'm not fully sure of the implications from this change. We currently are running a 3 node production HA cluster with 1.21 and I don't want to disrupt the cluster state. I also tried adding a ``Service`` ([see here](https://github.com/prometheus-operator/prometheus-operator/issues/1859#issuecomment-437740104)), however I couldn't manage to get it work quite yet, it would be the preferred solution tho

**Comment by Pflegusch** [comment]
@h4wkmoon did you find a suitable solution for this?

**Comment by h4wkmoon** [comment]
Nope.
As far as I know, Services need pods. In the kubernetes I've worked on, core kubernetes components were static pods. Correct me if I'm wrong, but in the case of microk8s, they are just processes.

**Comment by nenadalm** [comment]
I managed to get rid of the alerts.

Used chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**chart config**
```yaml
kubeControllerManager:
  endpoints:
    - <microk8s_ip>
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeScheduler:
  endpoints:
    - <microk8s_ip>
```

**/var/snap/microk8s/current/args/kube-controller-manager**
```
--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
```

**/var/snap/microk8s/current/args/kube-scheduler**
```
--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
# --address=127.0.0.1
```

references:
- https://microk8s.io/docs/external-lma
- https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
- https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

**Comment by larivierec** [comment]
> `--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics`

i'm guessing you commented out the 127.0.0.1 from both `kube-controller-manager` and `kube-scheduler`?

**Comment by larivierec** [comment]
> I managed to get rid of the alerts.
> 
> Used chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
> 
> **chart config**
> 
> ```yaml
> kubeControllerManager:
>   endpoints:
>     - <microk8s_ip>
>   service:
>     port: 10257
>     targetPort: 10257
>   serviceMonitor:
>     https: true
>     insecureSkipVerify: true
> kubeScheduler:
>   endpoints:
>     - <microk8s_ip>
> ```
> 
> **/var/snap/microk8s/current/args/kube-controller-manager**
> 
> ```
> --authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
> ```
> 
> **/var/snap/microk8s/current/args/kube-scheduler**
> 
> ```
> --authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
> # --address=127.0.0.1
> ```
> 
> references:
> 
>     * https://microk8s.io/docs/external-lma
> 
>     * https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
> 
>     * https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

i'm guessing you commented out the 127.0.0.1 from both kube-controller-manager and kube-scheduler?

**Comment by h4wkmoon** [comment]
Thanks. I will give it try. As I, like you did, removed the embedded prometheus to use the chart form the promtheus community.

The parameters that need to se in /var/snap/.... should be default, imo.

**Comment by larivierec** [comment]
tried this, seems to work only for the KubeScheduler and not the KubeControllerManager

**Comment by larivierec** [comment]
i followed https://microk8s.io/docs/external-lma
omitting the --show-hidden-metrics-for-version  (i didn't need it

i added the following
kube-controler-manager:
```
--bind-address 	0.0.0.0
--secure-port 	10257
```
for this i had to redeploy the kube-prometheus stack helm chart using this port and https with verify security `off`

kube-proxy:
```
--metrics-bind-address 	0.0.0.0:
```

**Comment by larivierec** [comment]
It appears that kube-scheduler and kube-controller-manager run on https now.
https://microk8s.io/docs/services-and-ports#heading--auth

you'll have to set it up so that the `serviceMonitors` ignore the ssl cert and use `https: true`

**Comment by larivierec** [comment]
Also, pretty sure this can be closed

**Comment by balchua** [comment]
i got something here that works for me.

# Steps to enable controller-manager, scheduler and kube-proxy metrics in Prometheus

## Controller manager
Before prometheus can successfully scrape the controller manager's metrics endpoint, you need to edit the file `/var/snap/microk8s/current/args/kube-controller-manager` with the following

```
...
--address=0.0.0.0
--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
...
```
This make sure that the controller manager is listening on any interface.

## Scheduler 
Before prometheus can successfully scrape the kube scheduler metrics endpoint, you need to edit the file `/var/snap/microk8s/current/args/kube-scheduler` and add or edit this

```
...
--address=0.0.0.0
--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
...
```
This make sure that the scheduler is listening on any interface.

## Kube Proxy
Before prometheus can successfully scrape the kube proxy metrics endpoint, you need to edit the file `/var/snap/microk8s/current/args/kube-proxy` and add this

```
...
--metrics-bind-address=0.0.0.0:10249
...
```

## Restart Kubelite or MicroK8s

Restarting kubelite

```shell
sudo snap restart microk8s.daemon-kubelite
```

Restarting MicroK8s

```shell
microk8s stop
microk8s start
```

## Apply the manifests

The default kube-prometheus do not include the kube-proxy `ServiceMonitor`

So apply the manifest `kube-proxy-servicemonitor.yaml`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-proxy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-proxy
spec:
  jobLabel: kube-proxy
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: http-metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-proxy
  namespaceSelector:
    matchNames:
    - kube-system
```    

## Create the Service and Endpoint manifests

These are the ports currently being used by MicroK8s.
If you change them please edit the manifest below.

```yaml

apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler
  labels:
    k8s-app: kube-scheduler
    app.kubernetes.io/name: kube-scheduler
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10259
    targetPort: 10259
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
    app.kubernetes.io/name: kube-controller-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10257
    targetPort: 10257
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-proxy
  labels:
    k8s-app: kube-proxy
    app.kubernetes.io/name: kube-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10249
    targetPort: 10249
    protocol: TCP    
```

## Endpoint manifest

Since all control plane in MicroK8s are systemd process and not pods, we need to manually create the `Endpoint`

The manifest below is a sample `Endpoint` that i use

The important area to edit are the `ip` and the `targetRef` in the `addresses` section. In this particular example the ip `192.168.2.15` and node `norse` are pointing to my own single node instance.
If you have multiple nodes running the control plane components, add them here.


```yaml
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-controller-manager
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.2.15
    targetRef:
      kind: Node
      name: norse
      uid: a466371b-4c17-4306-aa64-91d533b7b0a5
  ports:
  - name: https-metrics
    port: 10257
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-scheduler
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.2.15
    targetRef:
      kind: Node
      name: norse
      uid: a466371b-4c17-4306-aa64-91d533b7b0a5
  ports:
  - name: https-metrics
    port: 10259
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.2.15
    targetRef:
      kind: Node
      name: norse
      uid: a466371b-4c17-4306-aa64-91d533b7b0a5
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP    
```
