### ISSUE TITLE
Pods of a StatefulSet using microk8s-hostpath storage can be scheduled on another node

### ISSUE THREAD

**Issue by bgranvea** [canonical/microk8s#2618]
I have a cluster with 2 nodes and a StatefulSet which binds to persistent volumes created with storage class microk8s-hostpath.

As far as I understand, once the PV / PVC are created, the pods should always start on the same node because the volumes exist only locally. It seems that it is not the case.

Test case:

```
kubectl apply -f redis4.yaml

redis4.yaml:

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis-internal
  replicas: 4
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        volumeMounts:
        - name: datadir
          mountPath: /data
        resources:
          requests:
            memory: '2Gi'
            cpu: '0.5'
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      storageClassName: microk8s-hostpath
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 2Gi
```

After initial deployment:

```
# kubectl get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name
NODE                 NAME
dev-bgr-test2-u204   redis-0
dev-bgr-test2-u204   redis-1
dev-bgr-test1-u204   redis-2
dev-bgr-test2-u204   redis-3

# kubectl get pvc
NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
datadir-redis-0   Bound    pvc-3aaeab7b-6333-441a-9c62-f3242cde4bc1   2Gi        RWO            microk8s-hostpath   28s
datadir-redis-1   Bound    pvc-ec1ee15f-ef64-4494-8b8d-27ab30335bea   2Gi        RWO            microk8s-hostpath   24s
datadir-redis-2   Bound    pvc-0b03a0e8-ebf7-46d0-8f13-270350dd8037   2Gi        RWO            microk8s-hostpath   19s
datadir-redis-3   Bound    pvc-48276923-6c15-440b-bea5-076983afd65c   2Gi        RWO            microk8s-hostpath   16s
```

If I drain second node:

```
# kubectl drain dev-bgr-test2-u204 --ignore-daemonsets
node/dev-bgr-test2-u204 cordoned
WARNING: ignoring DaemonSet-managed Pods: kube-system/calico-node-vvzns
evicting pod default/redis-0
evicting pod default/redis-1
evicting pod default/redis-3
pod/redis-0 evicted
pod/redis-1 evicted
pod/redis-3 evicted
node/dev-bgr-test2-u204 evicted
```

I see that one of the pod previously running on node2 has been restarted on node1:

```
# kubectl get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name
NODE                 NAME
dev-bgr-test1-u204   redis-2
dev-bgr-test1-u204   redis-0
dev-bgr-test1-u204   redis-1
dev-bgr-test1-u204   redis-3
```

Reproduced with 1.19 and 1.21 (didn't checked other versions).

[inspection-report-20211001_070407.tar.gz](https://github.com/ubuntu/microk8s/files/7264862/inspection-report-20211001_070407.tar.gz)
