### ISSUE TITLE
Windows node network

### ISSUE THREAD

**Issue by mashbrno** [canonical/microk8s#2656]
I've installed Windows Server 2019 (as 2022 is not working at all with kube/microk8s). Used [this guide](https://microk8s.io/docs/add-a-windows-worker-node-to-microk8s) and node is correctly connected to the cluster, pods are scheduled and running. Unfortunatelly nginx ingress is not able to route traffic to them. Tried `docker container ls` which shows no ports for none of the containers. `kubectl port-forward` nor `kubectl logs` are not working neither. Tried to setup calico both without parameter and `vxlan`.

Snap channel: 1.22 (version 1.22.2)
Control nodes OS: Ubuntu 20.04.3 LTS

`pod.yaml`:

```
apiVersion: v1
kind: Pod
metadata:
  name: aspnet-test
spec:
  containers:
  - image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
    name: aspnet-test
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  nodeSelector:
    kubernetes.io/os: windows
```

and no opened ports
```
PS C:\> docker container ls
CONTAINER ID   IMAGE                                             COMMAND                   CREATED        STATUS        PORTS     NAMES
d23dbd59897e   mcr.microsoft.com/dotnet/framework/aspnet         "C:\\ServiceMonitor.eâ€¦"   15 hours ago   Up 15 hours             k8s_aspnet-test_aspnet-test_default_f824c9e2-b84d-4520-8c1d-d9e689e448ed_7
```

[inspection-report-20211013_163443.tar.gz](https://github.com/ubuntu/microk8s/files/7339057/inspection-report-20211013_163443.tar.gz)
