### ISSUE TITLE
nginx ingress on Ubuntu 21.10 VM in vSphere external_ip pending 

### ISSUE THREAD

**Issue by NathanDotTo** [canonical/microk8s#2737]
I am using microk8s with the nginx ingress on an Ubuntu VM 21.10. But I get:

[inspection-report-20211117_184901.tar.gz](https://github.com/ubuntu/microk8s/files/7557214/inspection-report-20211117_184901.tar.gz)

```
$ k --namespace ingress-nginx get services -o wide -w ingress-nginx-controller
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR
ingress-nginx-controller   LoadBalancer   10.152.183.89   <pending>     80:30122/TCP,443:31114/TCP   95s   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
```

My question here is whether the OOB config I am using below *should* work, and, if not, what can I do to make it so my cluster works in a single VM and the services are exposed via the VM public IP address?

I am following the instructions from here:

https://kubernetes.github.io/ingress-nginx/deploy/#quick-start

I install microk8s like this (using Terraform, hence the `each.value`):

```
sudo snap install microk8s --classic --channel=1.21/stable;sudo usermod -a -G microk8s ${each.value["user"]}
```

Then I install nginx ingress (see detailed logs below):

```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace
```

I then go on to try and use the ingress for gitea, but that does not work because, I think, the ingress controller is trying to use a load balancer, and there is no load balancer by default.

I install gitea with this Helm chart (https://gitea.com/NathanDotTo/helm-chart.git) altered to enable ingress on the hostname of the VM:

```
$ helm --debug install --dependency-update gitea . -f values.yaml
$ k get pods -A
NAMESPACE       NAME                                        READY   STATUS    RESTARTS   AGE
kube-system     calico-node-qnxft                           1/1     Running   0          85m
kube-system     calico-kube-controllers-f7868dd95-x6n7g     1/1     Running   0          85m
ingress-nginx   ingress-nginx-controller-77f4468d76-qqvfq   1/1     Running   0          10m
default         gitea-postgresql-0                          0/1     Pending   0          6m12s
default         gitea-0                                     0/1     Pending   0          6m12s
default         gitea-memcached-584956987c-4stwd            1/1     Running   0          6m12s
$ k get svc -A
NAMESPACE       NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
default         kubernetes                           ClusterIP      10.152.183.1     <none>        443/TCP                      86m
ingress-nginx   ingress-nginx-controller-admission   ClusterIP      10.152.183.197   <none>        443/TCP                      11m
ingress-nginx   ingress-nginx-controller             LoadBalancer   10.152.183.89    <pending>     80:30122/TCP,443:31114/TCP   11m
default         gitea-ssh                            ClusterIP      None             <none>        22/TCP                       6m49s
default         gitea-postgresql-headless            ClusterIP      None             <none>        5432/TCP                     6m49s
default         gitea-http                           ClusterIP      None             <none>        3000/TCP                     6m49s
default         gitea-memcached                      ClusterIP      10.152.183.230   <none>        11211/TCP                    6m49s
default         gitea-postgresql                     ClusterIP      10.152.183.154   <none>        5432/TCP                     6m49s

```

Detailed logs below.

```
$ helm --debug install --dependency-update gitea . -f values.yaml
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/teacher/scripts/k8s_setup/gitea/gitea-chart

Getting updates for unmanaged Helm repositories...
...
NAME: gitea
LAST DEPLOYED: Wed Nov 17 18:38:17 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
USER-SUPPLIED VALUES:
affinity: {}
clusterDomain: cluster.local
...
ingress:
  annotations: {}
  className: nginx
  enabled: true
  hosts:
  - host: cl-dev-host-00-k8s
    paths:
    - path: /
      pathType: Prefix
  tls: []

    test_db_connection

    echo '==== BEGIN GITEA CONFIGURATION ===='

    gitea migrate
    function configure_admin_user() {
      local ACCOUNT_ID=$(gitea admin user list --admin | grep -e "\s\+${GITEA_ADMIN_USERNAME}\s\+" | awk -F " " "{printf \$1}")
      if [[ -z "${ACCOUNT_ID}" ]]; then
        echo "No admin user '${GITEA_ADMIN_USERNAME}' found. Creating now..."
        gitea admin user create --admin --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}" --email "gitea@local.domain" --must-change-password=false
        echo '...created.'
      else
        echo "Admin account '${GITEA_ADMIN_USERNAME}' already exist. Running update to sync password..."
        gitea admin user change-password --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}"
        echo '...password sync done.'
      fi
    # Source: gitea/templates/gitea/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  labels:
    helm.sh/chart: gitea-0.0.0
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/version: "1.15.4"
    version: "1.15.4"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: "cl-dev-host-00-k8s"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 3000

NOTES:
1. Get the application URL by running these commands:
  http://cl-dev-host-00-k8s/

```

```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace
NAMESPACE: ingress-nginx
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The ingress-nginx controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace ingress-nginx get services -o wide -w ingress-nginx-controller'

An example Ingress that makes use of the controller:
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: example
    namespace: foo
  spec:
    ingressClassName: nginx
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                service:
                  name: exampleService
                  port:
                    number: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
      - hosts:
        - www.example.com
        secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls

```
