### ISSUE TITLE
microk8s config yields a url with https://none in it.  

### ISSUE THREAD

**Issue by eddieparker** [canonical/microk8s#2814]
I'm using vagrant to spin up a few VirtualBox VMs and ansible to configure a new cluster using microk8s 1.23.

I notice occasionally that `microk8s config` yields some weird results:

```
root@k8s-control-vm-01:~# microk8s config | grep -v 'certificate-authority-data'
Device "enp0s8
enp0s3" does not exist.
apiVersion: v1
clusters:
- cluster:
    server: https://none:16443
  name: microk8s-cluster
contexts:
# ... snip ...
```

Interestingly both enp0s8 and enp0s3 do exist (excerpt from ifconfig):

```
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.253.15  netmask 255.255.255.0  broadcast 192.168.253.255
        inet6 fe80::60:6aff:fe4c:ccdc  prefixlen 64  scopeid 0x20<link>
        ether 02:60:6a:4c:cc:dc  txqueuelen 1000  (Ethernet)
        RX packets 16  bytes 2735 (2.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 33  bytes 3484 (3.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.1  netmask 255.255.0.0  broadcast 10.0.255.255
        inet6 fe80::c00:ff:fe00:20  prefixlen 64  scopeid 0x20<link>
        ether 0e:00:00:00:00:20  txqueuelen 1000  (Ethernet)
        RX packets 3670  bytes 402598 (402.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1699  bytes 641352 (641.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

My network is attached to 10.0.2.1.  I've exiled the default vagrant interface to 192.168.253.15 as it was colliding before with my 10.0/16 domain (perhaps that's a source of my issue?).

I've attached the inspection report in case it's of any use.  Please let me know if there's more information worth sharing.

[inspection-report-20211228_033313.tar.gz](https://github.com/ubuntu/microk8s/files/7782615/inspection-report-20211228_033313.tar.gz)
