### ISSUE TITLE
1.22 worked, 1.23 caused "connection refused"

### ISSUE THREAD

**Issue by MatrixManAtYrService** [canonical/microk8s#2847]
I'm aware that installing microk8s inside of a circleci workflow isn't exactly standard usage, but I had it running reliably.  This week, it started failing: 

```
 RAN: /usr/bin/sh -c 'kubectl get namespaces -o json'
 STDOUT: The connection to the server 10.142.2.11:16443 was refused - did you specify the right host or port?
```

I went through the logs of successful runs and found this:
```
sudo snap install microk8s --classic
Download snap "microk8s" (2695) from channel "1.22/stable"  
```

The failing run had this:
```
sudo snap install microk8s --classic
Download snap "microk8s" (2848) from channel "1.23/stable"   
```

So I told snap to use the old version like below and the problem went away
```
sudo snap install microk8s --classic --channel=1.22/stable
```

I ssh'ed into the VM with the problem, here's an inspection report:

[inspection-report-20220118_040235.tar.gz](https://github.com/ubuntu/microk8s/files/7886103/inspection-report-20220118_040235.tar.gz)

Here's an edited-down version of the workflow that had the problem.  I removed all of the stuff that had nothing to do with microk8s (haven't tested the edited down version directly--I'm hoping it tells enough of the story--but I'm willing to test further if that would be helpful).

```yaml
version: 2.1
jobs:
  ci:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: large
    steps:
      - run:
          name: snap install
          command: sudo snap install microk8s --classic --channel=1.22/stable
      - run:
          name: "get config"
          command: |
            mkdir -p ~/.kube/
            sudo microk8s config >> ~/.kube/config
      - run:
          name: "enable microk8s features"
          command: sudo microk8s enable dns storage
      - run:
          name: "install kubectl"
          command: |
            cd ~/bin
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
      - run:
          name: "install helm"
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run:
          name: "prepare networking"
          command: |
            sudo snap install yq
            KUBE_IP=$(cat ~/.kube/config \
                | yq e '.clusters[0].cluster.server' - \
                | cut -d '/' -f3 \
                | cut -d ':' -f1)
            echo "      [plugins.\"io.containerd.grpc.v1.cri\".registry.mirrors.\"${KUBE_IP}:30500\"]
                    endpoint = [\"http://${KUBE_IP}:30500\"]" | sudo tee -a /var/snap/microk8s/current/args/containerd-template.toml
            sudo microk8s stop
            sudo microk8s start

            sudo mkdir -p /etc/docker
            echo '{"insecure-registries":["'$KUBE_IP':30500"]}' | jq . | sudo tee -a /etc/docker/daemon.json
            sudo service docker stop
            sudo service docker start

      - run:
          name: "do stuff"
          command: |
            cd qa-tb11c-dags
            export KUBECTL_COMMAND_HEADERS=false # https://github.com/kubernetes/kubectl/issues/1098
            export KUBECONFIG=/home/circleci/.kube/config
            /usr/bin/sh -c 'kubectl get namespaces -o json'

workflows:
  ci-workflow:
    jobs:
      - ci:
          context:
            - qa
```

Downgrading fixed it, so this isn't a high priority for me.  But if you guys think this is a microk8s bug then I'm happy to help with gathering info that would help with a fix.
