### ISSUE TITLE
Service with manually defined endpoints does not work 

### ISSUE THREAD

**Issue by LasseJacobs** [canonical/microk8s#2914]
I have a single node microk8s 'cluster' on my home-server. On this server I also have a jenkins instance running outside of the k8s cluster. I wanted to make the jenkins instance accessible from inside the cluster by creating a service without a selector and adding an endpoint myself explicitly:
endpoint:
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: external-jenkins
  namespace: jenkins  
subsets:
  - addresses:
    - ip: 192.168.0.242
    ports:
    - port: 8082
```
service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: external-jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8082
    name: web
```

However this does not work, any request to 'external-jenkins' fails. The jenkins instance itself works fine, if I curl the endpoint directly (192.168.0.242:8082) it works.

I did some debugging and found that the ip-tables entry rejects the traffic because there are no endpoints:
```
-A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "jenkins/external-jenkins:web has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 31333 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.152.183.190/32 -p tcp -m comment --comment "jenkins/external-jenkins:web has no endpoints" -m tcp --dport 8082 -j REJECT --reject-with icmp-port-unreachable
```

I checked the endpoint exists on the api-server. As per the kubernetes docs this setup should be possible. Any idea on what I might be doing wrong? Is it possible this edge-case is not supported by mircok8s?

I currently don't have access to my home-server but if needed I can add an export of `microk8s inspect` when I get back home.
