### ISSUE TITLE
Know Token Kubernetes Dashboard

### ISSUE THREAD

**Issue by SpyrosKptanopulos** [canonical/microk8s#292]
Hello,

How can I get the token to access the dashboard?

Thank you

**Comment by SpyrosKptanopulos** [comment]
I can not find the file or the route.

`movigoo@movigooapp_ha:~$ ll /snap/
total 24
drwxr-xr-x  5 root root 4096 Jan 23 15:39 ./
drwxr-xr-x 24 root root 4096 Jan 23 15:31 ../
drwxr-xr-x  2 root root 4096 Jan 24 02:29 bin/
drwxr-xr-x  4 root root 4096 Jan  4 01:56 core/
drwxr-xr-x  4 root root 4096 Jan 24 02:29 helm/
-r--r--r--  1 root root  548 Jan  3 21:00 README
movigoo@movigooapp_ha:~$
`

**Comment by TheNotary** [comment]
I can pull out the tokens fine with this command:

```
cat /snap/microk8s/current/known_token.csv
```

But when I paste in the number and letters for the token to `admin,admin,"system:masters"` and click 'sign in', the web dashboard doesn't doe anything.  

We're talking about this page here, right?


![dashboard_login](https://user-images.githubusercontent.com/799247/54694235-e91dd480-4af5-11e9-989b-77a2561cf253.png)

**Comment by ArmandoHerra** [comment]
@TheNotary worked, thanks!

`microk8s.kubectl -n kube-system get secret`
`microk8s.kubectl -n kube-system describe secret default-token-{xxxxx}`

**Comment by tdensmore** [comment]
I just installed **microk8s**, and have enabled **dns** and the **dashboard**. However when I try to access the dashboard UI, I get a sign-in screen. Using username `admin` and password `admin` does not work. I tried using the token, but the `known_token.csv` file is completely empty.  Any ideas?

**Comment by filipefelice** [comment]
if you want to disable this, use this command for edit

`microk8s.kubectl edit deployment/kubernetes-dashboard --namespace=kube-system`

and add enable-skip-login as below:

```
spec:
      containers:
      - args:
        - --auto-generate-certificates
        - --enable-skip-login
        image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
"/tmp/kubectl-edit-snu9z.yaml" 102L, 4077C    
```
