### ISSUE TITLE
HA Cluster setup doesn't generate HA kubeconfig/api server 

### ISSUE THREAD

**Issue by anubisg1** [canonical/microk8s#3083]
I have setup a microk8s HA cluster with 3 nodes. Among other things I have also enabled metal lb successfully.

How should I configure the api server so that’s actually LoadBalanced? This doesn't happen by default. 

microk8s config generates generates a different kubeconfig file for each node pointing to physical ip of the node where I ran the command on, and with different certificate and admin user password.

Ideally I’d be able to point to any of the 3 nodes via a load balancer vip as i expect to interact to the cluster remotely and i’d like to make sure i always reach it regardless of having a node down for any reason

**Comment by balchua** [comment]
Using metallb deployed as a pod to load balance the apiserver isn't trivial.  Before the anything can be deployed to kubernetes, kubelet needs to be able to reach the api server.

There's a discussion on this over at metallb

https://github.com/metallb/metallb/issues/168

**Comment by ktsakalozos** [comment]
@anubisg1, you may also want to add the IP the loadbalancer will give you in the `/var/snap/microk8s/current/certs/csr.conf.template` of each node so that the API servers use a certificate valid for that IP.

**Comment by anubisg1** [comment]
thank you both @balchua amd @ktsakalozos ! i will have a look now.

i can see that with K3S is doable easily via kube-vip , would that be an option

**Comment by balchua** [comment]
I haven't tried kube-vip, but i guess its doable, its kubernetes anyway.
Keepalived may also be an option.

**Comment by anubisg1** [comment]
ok, so this is what i managed to do, seems to be working fine.

I'm using kube-vip only for api-server HA. It could be used for svc loadbalancer but i wanted to keep metallb for that, for now.
starting from a totally blank installation.

1. install microk8s on the 3 nodes that form the control plane cluster: `sudo snap install microk9s --classic`
2. create new certificates on all nodes allowing for the VIP address:
2.1. edit `/var/snap/microk8s/current/certs/csr.conf.template` on all nodes
2.2. add `IP.99 = a.b.c.d` where `a.b.c.d` is the VIP address
2.3. generate new certificates on all nodes with `sudo microk8s refresh-certs`
3. form the cluster following the instructions listed here: https://microk8s.io/docs/high-availability 
4. prepare the basic cluster components `microk8s enable rbac helm3 dns`
5. install kube-vip via helm-chart (as a deamon set) 

```
microk8s helm3 repo add kube-vip https://kube-vip.io/helm-charts
microk8s helm3 repo update
microk8s helm3 install kube-vip kube-vip/kube-vip --namespace kube-system -f values.yaml
```

the file `values.yaml` can be found here https://github.com/kube-vip/helm-charts/blob/main/charts/kube-vip/values.yaml 
and i simply modified so that the following was configured

```
config:
  address: "192.168.0.30"  # This is my VIP

env:
  vip_interface: "eth0" # This is the interface, same on all nodes where the VIP is announced
  vip_arp: "true"  # mandatory for L2 mode
  lb_enable: "true" # enable load balancing
  lb_port: "16443" # description here -   https://kube-vip.io/architecture/#control-plane-load-balancing , changed only because microk8s used 16443 instead of 6443
  vip_cidr: "32"
  cp_enable: "true" # enable control plane load balancing
  svc_enable: "false" # disable SVC load balancing
  vip_leaderelection: "true" # mandatory for L2 mode
```

at this point we are done, i get a kubectl config from microk8s using `microk8s config` and simply make sure that the server IP is changed to the VIP instead of localhost used by default 

i will test a worker node join, but this is i think good enough for most people.

notice that the deamon set comes with a toileration so that will only run on control plane nodes and not on workers ones
