### ISSUE TITLE
Enable gpu addon in an offline method

### ISSUE THREAD

**Issue by m1nish1208** [canonical/microk8s#3111]
Hi,

We are already using offline install method to deploy microk8s using --> https://microk8s.io/docs/install-alternatives#heading--offline

Now we would like to enable `gpu` addon using an offline method. While checking few issues on github I found this issue 
-->  https://github.com/canonical/microk8s/pull/1295/files. 
If I understood it correctly we need to perform following steps: 
1. Add a hook --> /snap/microk8s/current/hooks/connect-plug-images
```
#!/usr/bin/env bash
set -eux

ARCH="$($SNAP/bin/uname -m)"
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH:/usr/bin:/usr/local/bin"

for image in $(ls $SNAP_COMMON/images/*.tar); do
    $SNAP/microk8s-ctr.wrapper image import $SNAP_COMMON/images/$image
done
```
2. Update /snap/microk8s/current/snapcraft.yaml file with following changes:
```
plugs:
  images:
    interface: content
    content: images
    target: $SNAP_COMMON/images

slots:
  microk8s:
    interface: content
    content: microk8s
    source:
      read: [$SNAP/.microk8s-info/microk8s]
```
2. save images under $SNAP_COMMON/images location for microk8s to look there first.

In this way will be be able to achieve offline installation of all such addons where container images are downloaded from internet? 

Kindly suggest.
