### ISSUE TITLE
Remote kubectl ignoring RBAC rule

### ISSUE THREAD

**Issue by adrianAzoitei** [canonical/microk8s#3155]
#### Summary
I have a **microk8s** single-node cluster running and would like to interact with it from a remote machine through **kubectl**.
I have created a **Role** configured to only allow access to resources in the **default** namespace, and a **RoleBinding** to couple it to a **User**.
So, following https://microk8s.io/docs/multi-user.
The problem is, if I use the [**Static Token File** authentication method](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-token-file), the user actually gets access to the entire cluster. I can, for example, list pods in the **kube-system** namespace. This is not an issue if I use [**x509 Client Certs**](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs) for authentication.

```bash
kubectl get pod -n kube-system
NAME                                         READY   STATUS    RESTARTS   AGE
coredns-7f9c69c78c-nfdzc                     1/1     Running   14         237d
calico-kube-controllers-f7868dd95-phnq9      1/1     Running   14         237d
dashboard-metrics-scraper-78d7698477-qpx5q   1/1     Running   14         237d
kubernetes-dashboard-85fd7f45cb-dlv4b        1/1     Running   14         237d
metrics-server-8bbfb4bdb-s6d7s               1/1     Running   14         237d
hostpath-provisioner-5c65fbdb4f-26f29        1/1     Running   14         237d
calico-node-6x96r                            1/1     Running   14         237d
```

#### What Should Happen Instead?
The RBAC rule should be respected with both kinds of authentication: Static Token File and x509 Client Certs. The rule is respected when using client certs.
```bash
kubectl get pod -n kube-system
Error from server (Forbidden): pods is forbidden: User "jenkins" cannot list resource "pods" in API group "" in the namespace "kube-system"
```

#### Reproduction Steps
1. Setup microk8s cluster.
2. Create **Role**.
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: jenkins
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create"]
```
3. Create **RoleBinding**.
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-role-binding
subjects:
- kind: User
  name: jenkins
  apiGroup: ""
roleRef:
  kind: Role
  name: jenkins
  apiGroup: ""
```
4. Add a token entry to `/var/snap/microk8s/current/credentials/known_tokens.csv` with columns `bearer_token,user,uid,"group1,group2,group3"`.
5. Add the user credentials to the microk8s config: `microk8s kubectl config set-credentials jenkins --token=<BEARER_TOKEN>`.
6. Fetch the client config with `microk8s config`.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: <HOST IP>
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: REDACTED
- name: jenkins
  user:
    client-certificate: <PATH_TO_CERT>/jenkins.crt
    client-key: <PATH_TO_KEY>/jenkins.key
```
7. On the remote, put the client config in ~/.kube/config, or another file and set the env. variable `KUBECONFIG` as the path to that file.
8. Set the `contexts.context.user` field in client config on the remote as the defined user (i.e. **jenkins** in this case).
9. Attempt to fetch pods from the **kube-system** namespace.
