### ISSUE TITLE
PodSecurity Standards on microk8s v1.24

### ISSUE THREAD

**Issue by m1nish1208** [canonical/microk8s#3280]
Hi I'm using microk8s version 1.24 on Ubuntu 20.04. 

I've enabled PodSecurity admission using FeatureGate. Restrictions on a namespace using labels is working fine. However when I'm trying to apply a cluster wide policy I'm getting following error:

The admission control config file is as follows:

```
admission-control-config
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
 path: cluster-level-pss.yaml

```
The cluster wide configuration file is as follows:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
 configuration:
   apiVersion: pod-security.admission.config.k8s.io/v1alpha1
   kind: PodSecurityConfiguration
   defaults:
     enforce: "baseline"
     enforce-version: "latest"
     audit: "baseline"
     warn: "baseline"
   exemptions:
     usernames: ["administrator"]
     runtimeClasses: []
     namespaces: ["kube-system","container-registry","gpu-operator-resources"]
```

Error is as follows:
```
Jun 27 21:25:32 administrator-virtual-machine microk8s.daemon-kubelite[658208]: Error: failed to initialize admission: couldn't init admission plugin "PodSecurity": no kind "AdmissionConfiguration" is registered for version "apiserver.config.k8s.io/v1" in scheme "vendor/k8s.io/pod-security-admission/admission/api/scheme/scheme.go:30"
Jun 27 21:25:32 administrator-virtual-machine microk8s.daemon-kubelite[658208]: F0627 21:25:32.233367 658208 daemon.go:67] API Server exited failed to initialize admission: couldn't init admission plugin "PodSecurity": no kind "AdmissionConfiguration" is registered for version "apiserver.config.k8s.io/v1" in scheme "vendor/k8s.io/pod-security-admission/admission/api/scheme/scheme.go:30"
```

Due to above error the kube-apiserver daemon isn't starting. Kindly let me know what am I missing here... 

Thanks.

**Comment by m1nish1208** [comment]
Following are steps to replica:

1. Add following line to kube-apiserver configuration file:
```
--feature-gates=PodSecurity=true
--enable-admission-plugins=PodSecurity
--admission-control-config-file=/var/snap/microk8s/current/args/admission-control-config
```
2.  Restart kube-apiserver daemon
3. Update admission-control-config with following:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  path: podsecurity.yaml
```
4. Add PodSecurityStandard labels on namespace.
```
pod-security.kubernetes.io/enforce: baseline
pod-security.kubernetes.io/enforce-version: v1.24
```
5. podsecurity.yaml has following snippet:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
 configuration:
   apiVersion: pod-security.admission.config.k8s.io/v1alpha1
   kind: PodSecurityConfiguration
   defaults:
     enforce: "baseline"
     enforce-version: "latest"
     audit: "baseline"
     warn: "baseline"
   exemptions:
     usernames: ["administrator"]
     runtimeClasses: []
     namespaces: ["kube-system","container-registry","gpu-operator-resources"]
``` 

But it doesn't seem to be working, I'm not able to apply exemptions on those namespaces. Kindly suggest.

**Comment by m1nish1208** [comment]
Trying to apply cluster-wide defaults & exemptions as per the documentation: https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/ 

Kindly suggest.

**Comment by neoaggelos** [comment]
Resolved in [Slack thread](https://kubernetes.slack.com/archives/CAUNWQ85V/p1656347143611469). There was an issue with the config file format.

For future reference:

```yaml
# /var/snap/microk8s/current/args/admission-control-config
---
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: EventRateLimit
  configuration:
    kind: Configuration
    apiVersion: eventratelimit.admission.k8s.io/v1alpha1
    limits:
    - type: Namespace
      qps: 50
      burst: 100
      cacheSize: 2000
    - type: User
      qps: 10
      burst: 50
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1alpha1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
      audit: "baseline"
      warn: "baseline"
    exemptions:
      usernames: ["administrator"]
      runtimeClasses: []
      namespaces: ["kube-system","container-registry","gpu-operator-resources"]
```

and then have the following lines appended to `/var/snap/microk8s/current/args/kube-apiserver`:

```
--feature-gates=PodSecurity=true
--enable-admission-plugins=PodSecurity
--admission-control-config-file=/var/snap/microk8s/current/args/admission-control-config
```

A restart is needed for the changes to take effect:

```
sudo snap restart microk8s
```

@m1nish1208 feel free to re-open if you have any extra issues. Thank you!
