### ISSUE TITLE
1.25 Metallb addon does not reply to LoadBalancer IP ARP requests

### ISSUE THREAD

**Issue by Tra5is** [canonical/microk8s#3421]
#### Summary
A fresh install of 1.25/stable or 1.25-strict/stable with metallb enabled does not reply to ARP requests for LoadBalancer services. 

1.24 works normally. 

#### What Should Happen Instead?
Services of type LoadBalancer should be accessible to external machines via their External IP, without any additional changes or modification. 

#### Reproduction Steps
1. > snap install microk8s --classic --channel=1.25/stable (OR snap install microk8s --channel=1.25-strict/stable)
2. > microk8s enable metallb:192.168.2.200-192.168.2.230
3. > helm repo add cowboysysop https://cowboysysop.github.io/charts/
4. > helm install --create-namespace -n whoami --set service.type=LoadBalancer whoami cowboysysop/whoami
* on a different machine on the network:
5. PS > $ip = kubectl get svc --namespace whoami whoami --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}"
6. PS > curl http://$ip

Error: "Unable to connect to the remote server"

7. PS > arp -a

Indicates there is no arp entry for $ip

Things I've tried to fix it. 

* Enabled promiscuous mode on eth0 and xx.calico interfaces
* Use explicit config to enable L2/ARP mode 
  * this removes the AddressPool CRD that was created during step 2.

Tried with configs:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: arp
      arp-network: 192.168.2.0/24
      cidr:
      - 192.168.2.200/29
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: arp
      addresses:
      - 192.168.2.200-192.168.2.230
```

Reverting to 1.24 results in the arp requests working normally and showing in the arp tables.

#### Introspection Report
[inspection-report-20220903_113543.zip](https://github.com/canonical/microk8s/files/9483193/inspection-report-20220903_113543.zip)
(pruned to logs from today's repro)

#### Can you suggest a fix?
Fix unknown

#### Are you interested in contributing with a fix?
yes

**Comment by neoaggelos** [comment]
Hi @Tra5is 

Thank you for bringing this up. The simplest way to fix this for clusters that are already deployed, is to apply an L2Advertisement resource like this. This tells MetalLB speaker pods to respond to ARP packets as needed.

```yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertise-all-pools
  namespace: metallb-system
```

For more complex setups, see https://metallb.org/configuration/#announce-the-service-ips

We also have a fix in https://github.com/canonical/microk8s-core-addons/pull/92, so the next bug-fix release will include it as well. Thanks again!
