### ISSUE TITLE
ingress HTTPS HTTP/2 without TLS returns 502 Bad Gateway

### ISSUE THREAD

**Issue by khteh** [canonical/microk8s#3475]
#### Summary

`ingress.yml`:
```
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress 
  namespace: default 
  annotations:
#    kubernetes.io/ingress.class: nginx - Not needed when ingressClassName is used below
    nginx.ingress.kubernetes.io/ssl-redirect: "false" 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
  labels: 
    app: ingress 
spec:
  ingressClassName: public
  rules:  
  - host: 
    http:   
      paths:  
      - pathType: Prefix
        path: /aspnetcorewebapi(/|$)(.*)
        backend:
          service:
            name: svc-aspnetcorewebapi
            port:
              number: 443
```
```
$ k describe ingress ingress
Name:             ingress
Labels:           app=ingress
Namespace:        default
Address:          127.0.0.1
Ingress Class:    public
Default backend:  <default>
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /aspnetcorewebapi(/|$)(.*)   svc-aspnetcorewebapi:443 (10.1.207.208:443,10.1.207.240:443)
```
```
$ k describe svc svc-aspnetcorewebapi
Name:              svc-aspnetcorewebapi
Namespace:         default
Labels:            app=aspnetcorewebapi
                   component=aspnetcorewebapi
Annotations:       <none>
Selector:          app=aspnetcorewebapi,component=aspnetcorewebapi
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              https  443/TCP
TargetPort:        https/TCP
Endpoints:         10.1.207.208:443,10.1.207.240:443
Session Affinity:  None
Events:            <none>
```
```
$ curl -v --insecure --http2 https://localhost/aspnetcorewebapi/
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Sep 29 05:28:07 2022 GMT
*  expire date: Sep 29 05:28:07 2023 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x564a71714e80)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /aspnetcorewebapi/ HTTP/2
> Host: localhost
> user-agent: curl/7.81.0
> accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 502 
< date: Thu, 29 Sep 2022 09:24:29 GMT
< content-type: text/html
< content-length: 150
< strict-transport-security: max-age=15724800; includeSubDomains
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host localhost left intact
```
#### Reproduction Steps

1. ...
2. ...

#### Are you interested in contributing with a fix?

[inspection-report-20220929_174644.tar.gz](https://github.com/canonical/microk8s/files/9673390/inspection-report-20220929_174644.tar.gz)
