### ISSUE TITLE
Restart microk8s with GPU enabled via addon fails to provide GPU to instances

### ISSUE THREAD

**Issue by Barteus** [canonical/microk8s#3500]
#### Summary
The VM (AWS p3.2xlarge) with Microk8s (GPU addon enabled) restarted the pods with GPU. The "workload" Pod which has access to GPU was in the Running state way before the NVIDIA GPU operator was.

#### What Should Happen Instead?
After restart, the Pod with GPU assigned should have a working GPU. I had to recreate the Pod after NVIDIA operator Pods were recreated to get the GPU working.

#### Reproduction Steps
1. Install GPU on VM
2. Install microk8s
3. Microk8s enable GPU
4. Create the Pod with GPU
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: super-cuda
    image: nvcr.io/nvidia/cuda:11.7.1-devel-ubuntu20.04
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
        limits:
          nvidia.com/gpu: 1
```
5. Restart the VM.
6. Wait for all the Pods to be in status Running or Completed
7. Try running any workload on the Pod. -> does not see the GPU 

#### Introspection Report
[inspection-report-20221011_115139.tar.gz](https://github.com/canonical/microk8s/files/9754821/inspection-report-20221011_115139.tar.gz)

#### Workaround
Redeploy/destroy the Pod with GPU attached. It starts working correctly again.
