### ISSUE TITLE
[microk8s 1.25] KubeletNotReady status error for single node cluster of jetson nano 

### ISSUE THREAD

**Issue by AjayKumar4** [canonical/microk8s#3501]
```
Ready            False   Tue, 11 Oct 2022 15:27:38 +0100   Tue, 11 Oct 2022 15:12:09 +0100   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

<img width="1462" alt="Screenshot 2022-10-11 at 15 29 44" src="https://user-images.githubusercontent.com/12373874/195119442-8faad595-cae3-4d3d-84dc-cd872aa297f5.png">

[inspection-report-20221011_152323.tar.gz](https://github.com/canonical/microk8s/files/9757002/inspection-report-20221011_152323.tar.gz)

Workaround
Downgrade the microk8s to 1.24 will solve this issue

**Comment by neoaggelos** [comment]
Hi @AjayKumar4 

Thank you for reporting this. I see the following failure in the cluster-dump that you sent:

```
MountVolume.SetUp failed for volume \"bpffs\" : hostPath type check failed: /sys/fs/bpf is not a directory
```

Can you attempt the following:

```
sudo snap install microk8s --channel 1.25 --classic
sudo vim /var/snap/microk8s/current/args/cni-network/cni.yaml
```

Inside the file, find and remove the following two sections and remove them:

```yaml

# (around line 4532)
             - name: bpffs
               mountPath: /sys/fs/bpf


# (around line 4558)
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
            type: Directory
```

Afterwards, re-apply the file with:

```
sudo microk8s kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml
```
