### ISSUE TITLE
Kubectl commands successfull, but /var/snap/microk8s/4374/args/kubectl: permission denied 

### ISSUE THREAD

**Issue by LukasIAO** [canonical/microk8s#3800]
#### Summary

When using any kubectl command such as `kubectl get pods`, as a non-admin user, the command succeeds, but I also get the error message `cat: /var/snap/microk8s/4374/args/kubectl: permission denied`.  The file in question is empty.

```
lukas-czurgel@DGX:~$ kubectl get pods
cat: /var/snap/microk8s/4374/args/kubectl: Permission denied
NAME             READY   STATUS      RESTARTS   AGE
cuda-vectoradd   0/1     Completed   0          5d19h
```

Changing the execute permissions to `/var/snap/microk8s/4374/args/` from `drwxrwx---` to `drwxrwx--x` fully breaks the kubectl command, leading to: `/snap/microk8s/4374/microk8s-kubectl.wrapper: line 22: /var/snap/microk8s/4374/args/kubectl-env: Permission denied`. The kubectl-env file contains a single line:

`export KUBECONFIG=SNAP_DATA/credentials/client.config`

Permissions in  the 4374 directory:

```
dgx-admin@DGX:/var/snap/microk8s/4374/args$ ls -al
total 84
drwxrwx---  3 root microk8s 4096 Feb 27 17:44 .
drwxr-xr-x 12 root root     4096 Feb  7 13:28 ..
-rw-rw----  1 root microk8s  120 Feb  7 13:23 cluster-agent
drwxrwx---  2 root microk8s 4096 Feb  7 13:23 cni-network
-rw-rw----  1 root microk8s  167 Feb  7 13:23 containerd
-rw-rw----  1 root microk8s  996 Feb  7 13:23 containerd-env
-rw-rw----  1 root microk8s 3461 Feb  7 13:39 containerd-template.toml
-rw-rw----  1 root microk8s 3484 Feb 14 08:20 containerd.toml
-rw-rw----  1 root microk8s   64 Feb  7 13:23 ctr
-rw-rw----  1 root microk8s  312 Feb  7 13:23 etcd
-rw-rw----  1 root microk8s  250 Feb  7 13:23 flanneld
-rw-rw----  1 root microk8s   56 Feb  7 13:23 flannel-network-mgr-config
-rw-rw----  1 root microk8s  502 Feb  7 13:23 flannel-template.conflist
-rw-rw----  1 root microk8s   17 Feb  7 13:23 ha-conf
-rw-rw----  1 root microk8s 1248 Feb  7 13:23 kube-apiserver
-rw-rw----  1 root microk8s  399 Feb  7 13:23 kube-controller-manager
-rw-rw-r--  1 root microk8s    0 Feb  7 13:23 kubectl
-rw-rw----  1 root microk8s   54 Feb  7 13:23 kubectl-env
-rw-rw----  1 root microk8s  713 Feb  7 13:28 kubelet
```
Im not sure if this is indicative of a deeper issue or if it can be safely ignored. in the latter case, I would still like to get rid of the error message.

#### What Should Happen Instead?

I would expect the user to be able to execute kubectl commands without the mentioned error message. But I'm unsure if i should mess with file permissions in the `args` directory.
#### Reproduction Steps

microk8s version: 1.22
OS: DGX-OS 5.4.1 (ubuntu 20.04)
Single-node cluster

kube-config of the user:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: REDACTED
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: lukas-czurgel
  name: lukas-czurgel-default
current-context: lukas-czurgel-default
kind: Config
preferences: {}
users:
- name: lukas-czurgel
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

The cluster does not currently have the RBAC add-on enabled and is not part of the microk8s group.

-
