### ISSUE TITLE
Changing service CIDR more easier

### ISSUE THREAD

**Issue by kanimaru** [canonical/microk8s#3940]
#### Summary
The 1.27 feature of launch configurations are nice you can set CIDR for Pods before starting the cluster. But its missing to set the Service CIDR also that would be more important cause when you change Pod CIDR its easy to restart every pod. But Services can't be recreated that easily so you have to manually remove and add every service again. So an Option would be to specifiy the Service Cidr also in launch configurations. Or make it possible to install Microk8s in a stopped state that you can tweak the service CIDR manually before starting for the first time.

#### Why is this important?
Cause changein Service CIDR is tedious otherwise.

#### Are you interested in contributing to this feature?
No, sorry not enough time and probably not enough knowledge yet

**Comment by neoaggelos** [comment]
Hi @kanimaru

Thank you for raising this. Indeed the launch configurations feature is a means of providing "building blocks" instead for people to achieve their desired setup.

I will make sure to update the documentation with such an example. To get started with setting the cluster service CIDR, you can try the following launch configuration (ensure all control plane nodes use this):

```yaml
---
version: 0.1.0
extraKubeAPIServerArgs:
  --cluster-service-ip-range: 10.200.0.0/16
# add a subject alternate name for the Kubernetes service IP
extraSANs:
  - 10.200.0.1
```

Note that this setup, enabling the DNS addon will not work as expected, since the addon will try to use the hardcoded address 10.152.183.10. To get around this problem, you can do:

```bash
# if enabled already, disable
sudo microk8s disable dns 

# update the service IP address on the DNS addon manifest, e.g. to 10.200.0.10
sudo sed -i 's/10.152.183.10/10.200.0.10/g' /var/snap/microk8s/common/addons/core/addons/dns/*

# enable DNS, now it will use the new service IP and come up properly
sudo microk8s enable dns
```

**Comment by neoaggelos** [comment]
Now that https://github.com/canonical/microk8s-core-addons/pull/181 is merged and released, it is possible to do the following to set the service IP for the CoreDNS service as well:

```yaml
---
version: 0.1.0
extraKubeAPIServerArgs:
  --service-cluster-ip-range: 10.200.0.0/16
# add a subject alternate name for the Kubernetes service IP
extraSANs:
  - 10.200.0.1
addons:
  - name: dns
    args: [/etc/resolv.conf, 10.200.0.10]
```
