### ISSUE TITLE
Forbidden error after RBAC is enabled

### ISSUE THREAD

**Issue by davgia** [canonical/microk8s#3965]
#### Summary
Enabling RBAC through `microk8s enable rbac` causes some kubectl to fail even if the permissions are set correctly.

``` sh
~ kubectl auth can-i get pods
yes
~ kubectl get pods -n vault
NAME      READY   STATUS    RESTARTS      AGE
vault-0   1/1     Running   1 (73m ago)   90d
~ kubectl auth can-i get pods/log
yes
~ kubectl logs vault-0 -n vault
Error from server (Forbidden): Forbidden (user=127.0.0.1, verb=get, resource=nodes, subresource=proxy) ( pods/log vault-0)
~ kubectl auth can-i create pods/exec
yes
~ kubectl exec -it vault-0 -n vault -- sh
error: unable to upgrade connection: Forbidden (user=127.0.0.1, verb=create, resource=nodes, subresource=proxy)
~ kubectl auth can-i '*' '*'
yes
```

The user I'm using is bind to cluster-admin role and should be able to perform all commands above.
Disabling rbac results in the commands above to work properly.

#### What Should Happen Instead?
The kubectl commands should not fail.

#### Reproduction Steps

1. install microk8s on ubuntu 20.04 LTS
2. enable rbac (`microk8s enable rbac`)
3. try the commands above

#### Introspection Report

[inspection-report-20230511_153720.tar.gz](https://github.com/canonical/microk8s/files/11452784/inspection-report-20230511_153720.tar.gz)

**Comment by neoaggelos** [comment]
Hi @davgia, can you provide an example of how you created the user and what are the exact permissions you have assigned? the `ClusterRole` and `ClusterRoleBinding` objects should be enough.

One thing I notice is that your `kubectl auth can-i` is for the default namespace, whereas you attempt to run the commands on the `vault` namespace. Could this be the issue?

**Comment by davgia** [comment]
Hi @neoaggelos,

I've run the namespaced auth can-i commands, here is the result:

``` sh
~ kubectl auth can-i get pods -n vault
yes
~ kubectl auth can-i get pods/log -n vault
yes
~ kubectl auth can-i create pods/exec -n vault
yes
~ kubectl auth can-i '*' '*' -n vault
yes
```

Here is the `ServiceAccount` and the `ClusterRoleBinding`:

``` yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: rbac
    app.kubernetes.io/name: rbac
  name: davide
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rbac
    app.kubernetes.io/name: rbac
  name: davide
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: davide
  namespace: kube-system
```
