### ISSUE TITLE
procMount Unmasked is ignored

### ISSUE THREAD

**Issue by prabhat-org** [canonical/microk8s#3986]
#### Summary
When I try setting up procMount to Unmasked, it is ignored and Default is being set.

I checked with Microk8s 1.26 and 1.24 version.

#### What Should Happen Instead?
It should allow setting it up or error out if Unmasked does not exists.

#### Reproduction Steps

1. Deploy below manifest
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount-unmasked
  labels:
    app: nginx-proc-mount
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      procMount: Unmasked
```
2. check the deployed and see the procMount

#### Introspection Report

[inspection-report-20230522_172344.tar.gz](https://github.com/canonical/microk8s/files/11527304/inspection-report-20230522_172344.tar.gz)

#### Can you suggest a fix?

I have not tried it with any other kubernetes flavor but IMP, it should error out instead of silently setting it to Default.
