### ISSUE TITLE
Define Custom CIDR (including coreDNS) during installation of microk8s.

### ISSUE THREAD

**Issue by pliakas** [canonical/microk8s#4128]
#### Summary
During installation, it will be very helpful to define in one place the IP ranges that you want to use for all the microk8s components. 

#### Why is this important?
When microk8s is used in corporate environment, in many cases there is conflict in IP ranges with vpn clients (e.g. cisco vpn anyconnect) and other corporate firewall strategy. A similar cases was raised here: https://github.com/canonical/microk8s/issues/276#issuecomment-687663776

Where these steps are very helpful, there is a lot of manual work to make it work. I would propose to add this as a feature so, any user can easily change the IP ranges in the whole microk8s environment. 

#### Are you interested in contributing to this feature?
yes

**Comment by sachinkumarsingh092** [comment]
Hey @pliakas, starting from MicroK8s v1.28, you can do this with launch configurations[1].
Here's a sample launch config to do this:
```
---
version: 0.1.0
extraCNIEnv:
  IPv4_SUPPORT: true
  IPv4_CLUSTER_CIDR: 10.3.0.0/16
  IPv4_SERVICE_CIDR: 10.153.183.0/24
  IPv6_SUPPORT: true
  IPv6_CLUSTER_CIDR: fd02::/64
  IPv6_SERVICE_CIDR: fd99::/108
extraSANs:
  - 10.153.183.1
 ```
This launch config should be present before you deploy the cluster and then the internal services will take an IP from the given CIDR. You can use either IPv4 or IPv6 addresses.
[1]https://microk8s.io/docs/add-launch-config
