### ISSUE TITLE
Repeated nodeAssigned events on ingress service

### ISSUE THREAD

**Issue by frnmz** [canonical/microk8s#4131]
#### Summary
Our app, which has a login section, always gets disconnected whenever the 'nodeAssigned' event occurs. This happened on MicroK8s version 1.27.4, revision 5643.
Below is the description of the ingress service:
```
Name:                     ingress-service
Namespace:                ingress
Labels:                   <none>
Annotations:              <none>
Selector:                 name=nginx-ingress-microk8s
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.152.183.224
IPs:                      10.152.183.224
IP:                       10.10.13.100
LoadBalancer Ingress:     10.10.13.100
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  32176/TCP
Endpoints:                10.1.174.193:80,10.1.175.65:80,10.1.200.1:80 + 2 more...
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  32174/TCP
Endpoints:                10.1.174.193:443,10.1.175.65:443,10.1.200.1:443 + 2 more...
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age                     From             Message
  ----    ------        ----                    ----             -------
  Normal  nodeAssigned  2m16s (x16 over 9m19s)  metallb-speaker  announcing from node "dcim-worker2" with protocol "layer2"
```

#### What Should Happen Instead?
With the same app and the same manifest this does not happened on microk8s  v1.23.17 revision 4916

#### Reproduction Steps

This is simple yaml that we use to deploy ingress and kube-dashboard
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.13.100
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443


```
```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: public
  tls:
    - hosts:
        - k8s-dcim.nexcloud.id
      secretName: star-nexcloud
  rules:
    - host: "k8s-dcim.nexcloud.id"
      http:
        paths:
          - path: /dashboard(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard

```

Could this be due to a difference in MetalLB versions, or is it related to our configuration?

Thanks!
[inspection-report-20230808_104904.tar.gz](https://github.com/canonical/microk8s/files/12289994/inspection-report-20230808_104904.tar.gz)
