### ISSUE TITLE
latest/edge v1.27.4 (5735) adding node to cluster failed

### ISSUE THREAD

**Issue by TecIntelli** [canonical/microk8s#4133]
Hello everybody,

#### Summary
We have tried to add a node to another to create a cluster. But this failed with the current (last) build (5735) of v1.27.4.
The joining process finished in the command line with:
`Waiting for this node to finish joining the cluster. .. .. .. ..`

But after this microk8s failed to start properly. 
`microk8s is not running. Use microk8s inspect for a deeper inspection.`

If we try to check the nodes with `microk8s kubectl get node` on the joining side we get:
`error: error loading config file "/var/snap/microk8s/5735/credentials/client.config": yaml: line 5: mapping values are not allowed in this context`

On the 'master' node we get listed just the 'master' node itself. But if we reinstall microk8s again and try to join to the named 'master' node, we get: `Connection failed. The joining node (10.0.1.23) is already known to dqlite (504).` 

#### What Should Happen Instead?
It should work without this issue like in v1.27.4 (5643) installed via snap (1.27/stable)

#### Reproduction Steps
Fresh installed microk8s instances via snap with default configuration.

1. Run `microk8s add-node` on the 'master' node
2. Run `microk8s join 10.0.1.22:25000/a4c2e97474936e0f6e3bc0936405ec21/31be174e7d37` on the joining node

Can anybody reproduce this behaviour? This might be a bug.
Thanks.

**Comment by ktsakalozos** [comment]
Hi @TecIntelli can you help me reproduce this? Could you share the inspection reports from both nodes?

**Comment by ktsakalozos** [comment]
@TecIntelli could you also share how the /var/snap/microk8s/5735/credentials/client.config looks like? Still trying to reproduce this.

**Comment by ktsakalozos** [comment]
I see these errors:
```
Jul 19 10:06:07 k8s-node-1 microk8s.daemon-cluster-agent[844]: 2023/07/19 10:06:07 [ERROR 400] "the hostname (k8s-node-2) of the joining node does not resolve to the IP \"172.31.27.125\". Refusing join"
Jul 19 10:06:07 k8s-node-1 microk8s.daemon-cluster-agent[844]: 2023/07/19 10:06:07 POST 400 "/cluster/api/v2.0/join" 117 bytes in 9.627751ms
Jul 19 10:06:30 k8s-node-1 microk8s.daemon-cluster-agent[844]: 2023/07/19 10:06:30 [ERROR 500] "invalid token"
Jul 19 10:06:30 k8s-node-1 microk8s.daemon-cluster-agent[844]: 2023/07/19 10:06:30 POST 500 "/cluster/api/v2.0/join" 25 bytes in 167.121µs
Jul 19 10:06:44 k8s-node-1 microk8s.daemon-cluster-agent[844]: 2023/07/19 10:06:44 [ERROR 400] "the hostname (k8s-node-3) of the joining node does not resolve to the IP \"172.31.31.7\". Refusing join"
```
Can you please make sure the hostnames of all nodes are resolvable on all nodes?

**Comment by TecIntelli** [comment]
@ktsakalozos here are the `/var/snap/microk8s/5735/credentials/client.config` of the joining node:

```
admin@k8s-node-2:~$ cat /var/snap/microk8s/5735/credentials/client.config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWWVubGtKQVJqS1U5aTZnVFpUS0MxRG5xOEljd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRGd3T0RFMU5UZ3lOMW9YRFRNegpNRGd3TlRFMU5UZ3lOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2TmZ4QkNXa3BGZFEzWDhxKzlROHpqbXRTbDdreDYwWEMrbjYKZ1g1TlFGNWxWWm5jbHNCNXRnajlZTG43NkQ5S2VsTWV3YWx5empVNUx1ZVdJcnlWSE9nUjB6SXJuTmE0REdYUgpSSGdNQnNidG1TNVhHVDlaY0x5QUlQbGRSOEVGOXp4YVFEdDJ2NFVleWpNdGFMTXg3Wkp3VjBkS0pHMEMyUlJyCjNQQWoxaTQvTXlJV1JGR3lTMk9WTzYzTjlNcFo4eWlQWHE4eTFuczAvZzc1akFnRjRyViswZStENUZ1RTZTdDcKNHVuNzlkU3cxS1NOMmhRMHdrVUViSmx2MVQ5RUQxUmE0UlRMczk1am1WRlJlRk9OYnd0bVZBZERRd1pvNStWVQpKQzB5YmsxcGFzMkJRbFUvZmFianRIczlwTzFQOXhxZ05rZmZQTkovOGxvOUZlWkxYUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWdmU1g0bnJ0a1IremRyZk5rZFNoQjRlNi9mY3dId1lEVlIwakJCZ3dGb0FVZ2ZTWDRucnQKa1IremRyZk5rZFNoQjRlNi9mY3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBamVEdTFLNldrc1FvbzYwcW1Fc3pxdDFnSmdPbVZaL3ZlZTNDNVd4ODI5Ui9TK1cxanRVeHlQRm9qRkJJClZFbXc3SDRSWjB3TENYSUEzQmdjVUFUZWFSUVdtYzdyWHdmMEprVkkxSEJ4NXpNM0JCMy94aEN4S29yMWt6TmkKV0RGaXoxdE9DaGJsb1JObEVpakpKSkFaKzlmQ1c2TFhmVVIxckVlRFlINkRiNFVyYm85aUdDTmtpNUdadnc4agoxbEVHWFpPRlY1VTRJWXpqL0dlS3pEdGZzdmsrSUlqTlVrcGYzYWhtd3pMdjcwL09zQk9Kc1Y1UU51OHFxR2EvCng1OTQwUkZrQ0dnVHVydEhXdVlwT0ovS2VJb3Flemkwd1V2bGV1MFpnWTNzcDJVWksrOVliNmV5SjZ1ZDYwZFIKa3o5Q1ZwcVp2Wmk2dE1DcGtYcFNKK3ZZQ3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6RENDQWJTZ0F3SUJBZ0lVVTN3c2pZMTdiTVRrMFNRSXNtd1dlK0xOUFRFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRGd3T0RFMk1EQTFNMW9YRFRNegpNRGd3TlRFMk1EQTFNMW93S1RFT01Bd0dBMVVFQXd3RllXUnRhVzR4RnpBVkJnTlZCQW9NRG5ONWMzUmxiVHB0CllYTjBaWEp6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0eWIxWmtmSlloUTQKQ2F6ajlabHRReXVwYjhUMEdrNEFrcGJiWWx4V0hEVTIyRjFqU0VFSjJWSVNjNmJzSlRjdkZvdy9KMlM1WGtMNApOQ2ZOU3pndW5NWjgxZklqY2wvR3E0Rk50NGErM1IrM2UxZFQyTUI4VFY3bENmb2VCVkhSTm9acG9WVHVCRmRuCmhzSnhGRFR1NVpxK21WTDJTMUNiUzY2SWZCaFRwbE5qaENxbU5qSDl3UWJiYURMNUZyRGs4akdpOVhOR1JicXUKYk1qS2JGRll4VzV2NTdmZmw2M3lnbHpJWUVYQlFNamR2WjRkTTkxaEhuWXZ2OUFwN2lGbGpqN3UvcStYS1B4RgprWU41bDlpZEVCWHROYjRaM0xKQ1hZNnFEU0duRmNLMWRDaHBsWjUvV3BPRWJCRW43UEtPWUFhUFdmNlRTWDZCCmFGdmRQKzJTSFFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJxRXBFV0NCYVJLL0QySGZ1Q1o3a1MKdDlXMStxSjl0L0x4VE45YmNLb1BaSmVrdEQxcGVNWHdjTDhmbHBPZzZwOEpCMWhrblFmMytrVGFsZXJPNDZCLwpNdVRUMk1TNThaVVV5T3BRa2FFNGMxOC9EdVQ3cXA2ZHR2aDhmeUIvRWpCa0U2WG02cmNlbWtXRUVpZ1RWRFRICklERkxoaDZtUHBRZzY1RUNkb2dqRTY2SVY1UkdqakE4b3JOanFHZEJ4K0NIR1hiYXZXaGN1dC9NaVlxMFBrVUEKSEpvQVNsS3RZZ2NwWElFeitNYlduWVByT0FhOXg0RXN5U3pKUXlqZVRiMkRTdURid2xydDk1WVlLQ2dxTHZLLwp1M2FLS25mOWxNZEw1a1kxcUVyaUxIUDVrQjJQZ0hQbERxL2FjZ3VoTlhFZnZWcmgxNFFYWWlqWTM2d3BtVzdsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdHliMVprZkpZaFE0Q2F6ajlabHRReXVwYjhUMEdrNEFrcGJiWWx4V0hEVTIyRjFqClNFRUoyVklTYzZic0pUY3ZGb3cvSjJTNVhrTDROQ2ZOU3pndW5NWjgxZklqY2wvR3E0Rk50NGErM1IrM2UxZFQKMk1COFRWN2xDZm9lQlZIUk5vWnBvVlR1QkZkbmhzSnhGRFR1NVpxK21WTDJTMUNiUzY2SWZCaFRwbE5qaENxbQpOakg5d1FiYmFETDVGckRrOGpHaTlYTkdSYnF1Yk1qS2JGRll4VzV2NTdmZmw2M3lnbHpJWUVYQlFNamR2WjRkCk05MWhIbll2djlBcDdpRmxqajd1L3ErWEtQeEZrWU41bDlpZEVCWHROYjRaM0xKQ1hZNnFEU0duRmNLMWRDaHAKbFo1L1dwT0ViQkVuN1BLT1lBYVBXZjZUU1g2QmFGdmRQKzJTSFFJREFRQUJBb0lCQUNPeTNrWXZXOXRZSVl3UgpQT1dVSUMzbGhzTVlXcFA5L0RLV1lQQ05HdU9vbzZZTW5kdHBnZWZ3RFZTcGhvSENmZFVoUlBZQ3RmYmZpczF2CnJKNHF0enNyblExK2d0WTZRTmtRL1ByMnNxRWJHNEpaQlNqTWErNFF2d2Z3em9VdTYxNTdXSDl2dEd6NE5GK1oKNnJ5TGpMMElLbnBzSjBHSzFwb3J6TUtUWTBxWnhYemZKdHlXbiswL3hqMC9xVnZ5K2IzaFdEU2VvNUI2ZUpxVgovaXgvTDBPSXBMTXdBSVo1d2VXVVJ4OS96Q2lKZjlZVVdQekxQOVQ4Zk83L3B0VVJsNkFiM2xaUURpVWgxQUE4CktvN1FpRmhJUkFDalJQQXZlZVBkNGU4UVBybWRSSFc2RGlLNU9FLy9US1krY0pRNE05enI4ek10c3ZoSm1yejQKYlZ5ZUpPa0NnWUVBOEkwRnpyNDJ1b0FyK0R2RXVHcGxSZjNrRmNhS3hWMnV6eXdCWGRESE1GVVIrY2ZCT1BMVAp0NklTb3ZuVVNDWkNHYnZpM3VoZXVib2ZSc0tTSFI5VjZjTWU3TWJ6RmVUVk51b2puM0FoQ3M4d3dIdVhrSzliCmp2Z21KL21BUVBMZGcra3E2S090Y1F2ZHpzMGQyNEl2aGlwdlVxa21hRDFVVm9GdDNDaWtkSU1DZ1lFQXd1bzUKa2JFd0hxbGFiOHg2VGhGcUFrSkhrK0NuQWI3c0VOcEhZNVJXZjNEMjJiRERlUVdRTVRDUnQ2bG1uaXdXeFV3OQpOTHVPd1FvUjJmZ1BaZzMrcDFQdTNDTUJvdDdvVHA5YTAzdGluWlNJYTYxTWlxR0d3Y0lwUTMyYUpnSkU2QTNECi9WZVoyNmtGWU51Y29FRVB2d25KR0k0SkpRa2JaYVpnRWI1dlhOOENnWUVBeDExWnJ0dGZLSHNKOWhZekdGUzEKMHFoMTNNWk1SUDg3M21BdVViNnpGNCtwOGtab0VmYlBHYWF0bzMxRFB2aldWOVdzVmVwb2Q2MldObU1VRGlibQpZWE5oc2dQQmZDZkh2bGVYWnBEY0VjVmVObWs0V0tXOVVHVEIydWVpTURJWS9UYkdaVUVpZ2txL2JxSDVXUEF3Cnl4Vm9aaTNpc3dvQldDQzFHSDVtcmxrQ2dZQXhzMVhnbjRTOG5NUlJzNXNRSXdLYjl0aVhqWFlvVE0yVzhvRzMKazVDR3lJQTVQQWhyNkk0KzdMcUxVV2U0TjFmTEVVaWVGS0V1K2VsWlloWlRHSWh4bEVaWTNaaENOb0tYNGF4ZwpOcHNMd1Y4VHpjbXhvOFJmemFtRjZ4WU9VUS9PK0F1Y291UzVqUnl3K082ME1rTFluSjhwWXJaVU9rRkJKeTVoCjkrUWZrd0tCZ0hrekdEWm8wMGhtbVlnUXhKQWhyaXRseGRKcEdXdGJXa21mK1BMZXM0d3kyaDZ3anhvTEtaUncKMUd5eDMwNUpZYWxyVnBYS3FWcHlXRHVVL0Z5RW9uNVdaUGwxejM2bEFIN1VFeG9jR1g2KzFGNWRQV3N2MDAwTQpNU2R2TG5CUC9DekZMZ2dkYW5GdjlqOUIxL0JQZnhleEVZSjJkYkxmdFVaUnNGZDdYMlo4Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

and here of the 'master' node:
 ```
admin@k8s-node-1:~$ cat /var/snap/microk8s/5735/credentials/client.config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWWVubGtKQVJqS1U5aTZnVFpUS0MxRG5xOEljd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRGd3T0RFMU5UZ3lOMW9YRFRNegpNRGd3TlRFMU5UZ3lOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2TmZ4QkNXa3BGZFEzWDhxKzlROHpqbXRTbDdreDYwWEMrbjYKZ1g1TlFGNWxWWm5jbHNCNXRnajlZTG43NkQ5S2VsTWV3YWx5empVNUx1ZVdJcnlWSE9nUjB6SXJuTmE0REdYUgpSSGdNQnNidG1TNVhHVDlaY0x5QUlQbGRSOEVGOXp4YVFEdDJ2NFVleWpNdGFMTXg3Wkp3VjBkS0pHMEMyUlJyCjNQQWoxaTQvTXlJV1JGR3lTMk9WTzYzTjlNcFo4eWlQWHE4eTFuczAvZzc1akFnRjRyViswZStENUZ1RTZTdDcKNHVuNzlkU3cxS1NOMmhRMHdrVUViSmx2MVQ5RUQxUmE0UlRMczk1am1WRlJlRk9OYnd0bVZBZERRd1pvNStWVQpKQzB5YmsxcGFzMkJRbFUvZmFianRIczlwTzFQOXhxZ05rZmZQTkovOGxvOUZlWkxYUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWdmU1g0bnJ0a1IremRyZk5rZFNoQjRlNi9mY3dId1lEVlIwakJCZ3dGb0FVZ2ZTWDRucnQKa1IremRyZk5rZFNoQjRlNi9mY3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBamVEdTFLNldrc1FvbzYwcW1Fc3pxdDFnSmdPbVZaL3ZlZTNDNVd4ODI5Ui9TK1cxanRVeHlQRm9qRkJJClZFbXc3SDRSWjB3TENYSUEzQmdjVUFUZWFSUVdtYzdyWHdmMEprVkkxSEJ4NXpNM0JCMy94aEN4S29yMWt6TmkKV0RGaXoxdE9DaGJsb1JObEVpakpKSkFaKzlmQ1c2TFhmVVIxckVlRFlINkRiNFVyYm85aUdDTmtpNUdadnc4agoxbEVHWFpPRlY1VTRJWXpqL0dlS3pEdGZzdmsrSUlqTlVrcGYzYWhtd3pMdjcwL09zQk9Kc1Y1UU51OHFxR2EvCng1OTQwUkZrQ0dnVHVydEhXdVlwT0ovS2VJb3Flemkwd1V2bGV1MFpnWTNzcDJVWksrOVliNmV5SjZ1ZDYwZFIKa3o5Q1ZwcVp2Wmk2dE1DcGtYcFNKK3ZZQ3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6RENDQWJTZ0F3SUJBZ0lVYlM2WlphSzB2TFNibmVmQzJweUt1d1d2UjBjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRGd3T0RFMU5UZ3lOMW9YRFRNegpNRGd3TlRFMU5UZ3lOMW93S1RFT01Bd0dBMVVFQXd3RllXUnRhVzR4RnpBVkJnTlZCQW9NRG5ONWMzUmxiVHB0CllYTjBaWEp6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1bGZvd01PWlFMM0YKV0VnOEo3UGt1YUxKWk5iTktWUk4ycGJ2dUExRERiTjM4RVhKRmxsT2VxRk5pNWV5TkdEaFVtK1dwSHlYZWZJRAppaXV5b2NYZFdZbHlCaGhhcjYyK2NaRVg3eGI2VlRjU242RkFrVmdPMytRdmFGMXJiWnh1b3RjRi85V253SmFDCjBsY1JHSFNneGREWWtSWk9ETlNMWEJNbGlYRXVIMlZodmJNQmFwdURmQ2FFQUFTY3NBN25HNzFyZjZaNTUrNlcKMVRzd1V2WWNMWUlEU2RsQ25mNkk5MitKZzlXUFNBWHlQb3BVMXRkRmt6TEJhVXBmOFlxaGYxWmZiN1dyS0RsUQozYnVXYVdxRy9iWmpOejNwTEpBSlZ0cE1SSzZ3QzBneU1LTnMrbXIwVlVuNnVoWG5wT2FMUk5jckZQdXl2SHgyCmpYLzE3K29YclFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUIvZ0NwWXF0dW9RUjNyTHlkc21IUEoKeiswbk5MUUY2UStEVVVSN2JoMXVESE9MMytVMFM1dDVpbHRYWFRUQWVoV1RhMnNpbnJrUmM3TUkybmYyS3VZQgpualVxK1JHamJSRW5RUmhPTTNLN2dLcWRqNFRmdHZTRzBUTWNmVTc4Qkg3dm9HeFNET3RlVmtrZENiUkRJNDF0CnBSakMrMThaZVhuczd5Ly9HMHBRK3I3Z0RSZVdOcllNd2NsUWQzSHhvdk4rNmprNzJ5dVU3SDJLclZENHJ2MTIKa3dpU3Y1QjJHS2dlUUxmTGljb1VqY1N3UE9FelVsVmI2NElFSFNldmkxc2k0Mk5GSThOVEhMZ2UxNXdRNGh3MwpUL0p4ZmdOVXpuWnZ6RkEyaXJpSHZIQitnV3hYTy9hYmMxbkFxWG5jU2dZa2RlV0ZMSUdEbmUya0tQNWpNbGswCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdWxmb3dNT1pRTDNGV0VnOEo3UGt1YUxKWk5iTktWUk4ycGJ2dUExRERiTjM4RVhKCkZsbE9lcUZOaTVleU5HRGhVbStXcEh5WGVmSURpaXV5b2NYZFdZbHlCaGhhcjYyK2NaRVg3eGI2VlRjU242RkEKa1ZnTzMrUXZhRjFyYlp4dW90Y0YvOVdud0phQzBsY1JHSFNneGREWWtSWk9ETlNMWEJNbGlYRXVIMlZodmJNQgphcHVEZkNhRUFBU2NzQTduRzcxcmY2WjU1KzZXMVRzd1V2WWNMWUlEU2RsQ25mNkk5MitKZzlXUFNBWHlQb3BVCjF0ZEZrekxCYVVwZjhZcWhmMVpmYjdXcktEbFEzYnVXYVdxRy9iWmpOejNwTEpBSlZ0cE1SSzZ3QzBneU1LTnMKK21yMFZVbjZ1aFhucE9hTFJOY3JGUHV5dkh4MmpYLzE3K29YclFJREFRQUJBb0lCQURvd1UyVkdieWZSV3J1cgpxdVUyL3JpZFJjaHdieFoxMWUzcGJpZ0tOQ01tSk5EcDZkWkp3d0QyTjlIY1ovQ0ZSRGRLMHo3QURVa3VNcjdGCjBIMUYzVTRsWm03UzBoYkQ2WkZySG84eG5MQlpoejVEeTNiWGlhV09pdU5MTU0zRXFLTy9BNGVWUDFJYmJmU2kKN1pxMmFMSDgrbk9zQkdsclFhMVo2VUhYRHZFTVhhVGh2VTZ5blJDVktxL3Q4cGJLbFVIWkVNelpuUXBPSkJ1ZApEdVVJdGMxOU1kWnd1RFJWb0R2OWJVN3JLbjhXRkRyN0lnNEROQmtwVVRmSWZySXNiSlV3MHNrZFFWZ0VNdFZCCkR4c0ZlYXd4S3gzNmNHaUh6MWdIb01IOEhzTGhUNDhBWHpJbnducTR6ZW9wUXNFVnNveE9hOXdFWUhRMG5wQU8KakJoT3BxRUNnWUVBN2dGa1BsMjltdElidVVxNGdMYkN6RWRya0xhZy9memptVzVRVTlBaGFsbGxRUkdvNmZSVgo0bTVqY2hCclptcFMweXREbWRraUNBU1BVcFlxV2kvRWRsNklka0lnMEFjeFBKTzNtajRSdXNjWXNaZFlKQkN2ClNRNGxLSUdTUXdSOVR6ZjROMzhZazhrMSs2cDZyUlFNcG1LT3p3VEJranlid1hqUTJvc01lT2tDZ1lFQXlHNlkKa0VoWlVKQVlZc3NhOTRBWUIwOUg0SERBYU9yd3lsNGlTSG42c3hPMWZjKzYrakZmY0phUHRaTW9NWkc1Yno3cQpqTXI2NXhCMEN5QWNMUm8yWGI2Nk9NTWFYRXVVdUwzTlBZMi95aHA4SUwzY3p2M1VCTExaSVpja2twRUh4cFdNCkM4NmU4QkkvY2ZoMlUrcm1JZlFmQUpRU0YzeFRBYWRIQ3BpVTdpVUNnWUVBck1rQjEyMENhMVZCbjBFcHRQZjUKYjRnaUJRc3cwWE00WUhqL2cvbERhUXZCUUgzcm5QMHZKSlZ6U0ttMjdzRWRwQVJ5clV3L01vYnM3YzNxclZLawpWRExJNnVHVEpMTTBBWUJUK0h3N0x0ZS9pNTROOVJEUDBEK2Vwa3Q2dllDUzRHSUhwM0p6aTBhMkZDQnRzeDB0CkdkWFBTMmR1aUJYTUZhYjZLTTV0blpFQ2dZQkI2QXdHdGFPWTJDa01vMWkwdGN3dzZ5THBiR240bGZpanNweDMKVkpUWk9jdmVHT2FVeXBObGhEeXhLamgzUkVIRGtONnplVE5UczVkVTZUUWFxSm5qN1lseWpNVW9RRG9oSFZoVgp1enlyaWxYeXRqdmJYSi9SQTdaZVUwTFZaeGMxZDR0YmZvL0l4VmRUZEs0RUhpT2FXcG12S1FGaDg2R2YwNCtLCnJtMmFlUUtCZ1FESFpETTkvbWJIekEwMWxud1ZYKzVsZEl3aXZLR0NkR0Ixd0tCZWxzL3J5VCtOYTFVU0YxZ0oKRERhYTk4eHdvQlhqYzI1MGwwTU9NTWtaTC9ZQlJleVFTZC93ZTlranBCaWZzbTdVQXNJbUdKWmJmcUthYTRNMgo1b0w4V3FjQUd4cm5yRUlWQTFBd3JQdTdJSXFhTVpueUpEd2Y1Z0xxSzgzd09SZVZ3dEtuamc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

The name resoltion should work on both nodes:

```
admin@k8s-node-1:~$ cat /etc/hosts
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
#127.0.1.1 ip-172-31-22-192.eu-central-1.compute.internal ip-172-31-22-192
127.0.1.1 ip-172-31-22-192.eu-central-1.compute.internal k8s-node-1
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

172.31.27.125 k8s-node-2
172.31.31.7 k8s-node-3
```

```
admin@k8s-node-1:~$ ping k8s-node-2
PING k8s-node-2 (172.31.27.125) 56(84) bytes of data.
64 bytes from k8s-node-2 (172.31.27.125): icmp_seq=1 ttl=64 time=0.218 ms

admin@k8s-node-1:~$ ping k8s-node-3
PING k8s-node-3 (172.31.31.7) 56(84) bytes of data.
64 bytes from k8s-node-3 (172.31.31.7): icmp_seq=1 ttl=64 time=0.594 ms
```

```
admin@k8s-node-2:~$ cat /etc/hosts
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
#127.0.1.1 ip-172-31-27-125.eu-central-1.compute.internal ip-172-31-27-125
127.0.1.1 ip-172-31-27-125.eu-central-1.compute.internal k8s-node-2
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

172.31.22.192 k8s-node-1
172.31.31.7 k8s-node-3
```

```
admin@k8s-node-2:~$ ping k8s-node-1
PING k8s-node-1 (172.31.22.192) 56(84) bytes of data.
64 bytes from k8s-node-1 (172.31.22.192): icmp_seq=1 ttl=64 time=0.205 ms

admin@k8s-node-2:~$ ping k8s-node-3
PING k8s-node-3 (172.31.31.7) 56(84) bytes of data.
64 bytes from k8s-node-3 (172.31.31.7): icmp_seq=1 ttl=64 time=1.03 ms
```


Regarding to your cited logs I just wondering why `k8s-node-3` is mentioned because I just tried to join `k8s-node-2` to `k8s-node-1` with `microk8s join 172.31.22.192:25000/fb9399f579f77bd8f5ed8a6305fced8d/9433c7ccd5d4`


Just to keep in mind, the joining process works with v1.27.4 (5643) as expected, that it should be an issue with the hosts. Or are there any changes regarding the joining process after build 5643?

Thnaks for your help.
