### ISSUE TITLE
Use one image registry for core services to work with L4 firewall policy out of the box

### ISSUE THREAD

**Issue by nobuto-m** [canonical/microk8s#4189]
#### Summary

Please consider using one single image registry when bootstrapping microk8s. Considering restrictive environments such as enterprise data centers, arbitrary access is not allowed. In that case, microk8s simply fails in the initialization phase and there is no easy way to configure L4 firewall to allow specific destinations in their allowed list.

#### What Should Happen Instead?

microk8s should be able to be bootstrapped under strict L4 firewall policy.

#### Reproduction Steps

1. `sudo snap install microk8s --channel 1.28 --classic`
2. `sudo microk8s.ctr image ls -q`

```
$ sudo microk8s.ctr image ls -q
docker.io/calico/cni:v3.25.1
docker.io/calico/cni@sha256:9a2c99f0314053aa11e971bd5d72e17951767bf5c6ff1fd9c38c4582d7cb8a0a
docker.io/calico/kube-controllers:v3.25.1
docker.io/calico/kube-controllers@sha256:02c1232ee4b8c5a145c401ac1adb34a63ee7fc46b70b6ad0a4e068a774f25f8a
docker.io/calico/node:v3.25.1
docker.io/calico/node@sha256:0cd00e83d06b3af8cd712ad2c310be07b240235ad7ca1397e04eb14d20dcc20f
docker.io/coredns/coredns:1.10.1
docker.io/coredns/coredns@sha256:a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e
registry.k8s.io/pause:3.7
registry.k8s.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
...
```

#### Introspection Report

[inspection-report-20230901_093255.tar.gz](https://github.com/canonical/microk8s/files/12496575/inspection-report-20230901_093255.tar.gz)

#### Can you suggest a fix?

Ideally, every image should come from rocks.canonical.com.

**Comment by nobuto-m** [comment]
In the log,

```
journalctl -u snap.microk8s.daemon-containerd.service | grep registry.k8s.io | tail -1
Sep 01 09:38:16 microk8s microk8s.daemon-containerd[5784]: time="2023-09-01T09:38:16.708927121Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:calico-node-jv2hs,Uid:87f90cf3-6202-49f4-816c-10e42741608d,Namespace:kube-system,Attempt:0,} failed, error" error="failed to get sandbox image \"registry.k8s.io/pause:3.7\": failed to pull image \"registry.k8s.io/pause:3.7\": failed to pull and unpack image \"registry.k8s.io/pause:3.7\": failed to resolve reference \"registry.k8s.io/pause:3.7\": failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.7\": dial tcp 34.96.108.209:443: connect: connection refused"
```

-> `failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.7\": dial tcp 34.96.108.209:443: connect: connection refused"`

**Comment by neoaggelos** [comment]
Hi @nobuto-m 

As a temporary workaround and in the process of exploring a workable solution for this, I have temporarily synced the pause, nginx-ingress and metrics-server images to the `rocks.canonical.com` repository like this:

```yaml
  - source: registry.k8s.io/pause:3.7
    target: rocks.canonical.com:5000/registry-k8s-io/pause:3.7
  - source: registry.k8s.io/ingress-nginx/controller:v1.8.0
    target: rocks.canonical.com:5000/registry-k8s-io/ingress-nginx/controller:v1.8.0
  - source: registry.k8s.io/metrics-server/metrics-server:v0.6.3
    target: rocks.canonical.com:5000/registry-k8s-io/metrics-server/metrics-server:v0.6.3
```

To use these, you can configure microk8s to use rocks.canonical.com as a mirror of registry.k8s.io like this:

```
echo '
[host."https://rocks.canonical.com:5000/v2/registry-k8s-io/"]
  capabilities = ["pull", "resolve"]
  override_path = true
' | sudo tee -a /var/snap/microk8s/current/args/certs.d/registry.k8s.io/hosts.toml
```

This would resolve your issue, as it will fallback to rocks.cc if registry.k8s.io is not accessible.

Note that at the moment this is not a guarantee/commitment that the images will stay in place or will be supported. This is more about exploring the viability of this option.

Feedback appreciated!
