### ISSUE TITLE
Image pull from ECR private registry is not working

### ISSUE THREAD

**Issue by rubel-ahammad** [canonical/microk8s#4371]
#### Summary
I am trying to configure a kubelet image credential provider to pull images from an ECR private registry. It looks like the 'ecr-credential-provider' gets registered but never pulls image from ECR. 

#### What Should Happen Instead?
I am expecting that the credential provider should pull images from my private registry.

#### Reproduction Steps
I have checked this with Microk8s 1.28.0 as well as 1.28.3. Here are the steps to reproduce.
1. Install Microk8s.
2. Create a new file `/var/snap/microk8s/common/credential-provider-config.yaml` with the following content.
```
apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
  - name: ecr-credential-provider
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    matchImages:
      - "*.dkr.ecr.*.amazonaws.com"
    defaultCacheDuration: 12h
```
3. Add following arguments in file `/var/snap/microk8s/current/args/kubelet`. The credential provider binary is `/usr/local/bin/ecr-credential-provider`.
```
--image-credential-provider-config=${SNAP_COMMON}/credential-provider-config.yaml
--image-credential-provider-bin-dir=/usr/local/bin/
```

#### Introspection Report
I have checked and confirmed that the ecr-credential-provider binary is working fine when I make the following request.
```
echo '{
  "apiVersion": "credentialprovider.kubelet.k8s.io/v1",
  "kind": "CredentialProviderRequest",
  "image": "XXXXXXXXXXX.dkr.ecr.XXXX.amazonaws.com/repository/image"
}' | /usr/local/bin/ecr-credential-provider
```

Please find the introspection report attached.

[inspection-report-20240115_130348.tar.gz](https://github.com/canonical/microk8s/files/13939167/inspection-report-20240115_130348.tar.gz)
