### ISSUE TITLE
Problem running a container witth mounted empty dir with memory medium

### ISSUE THREAD

**Issue by leandregagnonlewis** [canonical/microk8s#4405]
#### Summary

I am running microk8s on a single ubuntu VM with 32 Gi of RAM so memory is not an issue on the machine side.  I am trying to deploy a single replica of Nvidia Triton Inference Server wich allows to serve ML models. I am migrating from EKS to an on-prem solution and I am using exactly the same deployment config I used of EKS.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-triton-inference-server
  namespace: default
  labels:
    app: triton-inference-server
    chart: triton-inference-server-1.0.0
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-inference-server
      release: release-name
  template:
    metadata:
      labels:
        app: triton-inference-server
        release: release-name

    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"

      containers:
        - name: triton-inference-server
          image: "nvcr.io/nvidia/tritonserver:23.05-py3"
          imagePullPolicy: IfNotPresent

          resources:
            limits:
              nvidia.com/gpu: 0

          args: ["tritonserver", "--model-store=s3://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, 
                 "--model-control-mode=explicit",
                 "--load-model=vgg16_preprocessing",
                 "--load-model=bls_clust_v1",
                 "--log-verbose=2"]

          env:
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: triton-aws-credentials
                key: AWS_DEFAULT_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: triton-aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: triton-aws-credentials
                key: AWS_SECRET_ACCESS_KEY

          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /v2/health/ready
              port: http
          
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
              
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
```
Now the pod starts as usual. I can see in the logs that the files on s3 are properly downloaded so the problem is not with the credentials. But after a few seconds the pod crash without any indication. 

#### What Should Happen Instead?
The server should become healthy and wait for inference request to serve. I have try to deploy the server using docker on the same VM and it worked flawlessly so I guess the problem is with microk8s.

Here is my compose.yml
```
services:
  triton:
    image: "nvcr.io/nvidia/tritonserver:23.05-py3"
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    environment:
      AWS_DEFAULT_REGION: xxxxxxxxxxx
      AWS_ACCESS_KEY_ID: xxxxxxxxxxxxxxxxxxxx
      AWS_SECRET_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    command: ["tritonserver",
                 "--model-store=s3:/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
                 "--model-control-mode=explicit",
                 "--load-model=vgg16_preprocessing",
                 "--load-model=bls_clust_v1",
                 "--log-verbose=2"]
    shm_size: 2g

```

#### Reproduction Steps

1. Deploy Triton with the same manifest I have

 used. For the models to serve, try to use a simple VGG16 pretrained on imageNet deployed with a tensorflow backend as a saved Model files. This should cause the model to crash.
2. I have try to deploy both models independently and both make the pod to crash, but not at the same moment.

#### Introspection Report

[inspection-report-20240209_114600.tar.gz](https://github.com/canonical/microk8s/files/14224258/inspection-report-20240209_114600.tar.gz)
