### ISSUE TITLE
how to update metaalb address range 

### ISSUE THREAD

**Issue by nachiket96** [canonical/microk8s#4495]
Previously i added metallb address range using meicrok8s enable metallb there it prompt for ip address range now i want to update that but there is no config map for metallb how to do this

**Comment by neoaggelos** [comment]
Hi @nachiket96 

The resource you are looking for is `ipaddresspool/default-addresspool` in the `metallb-system` namespace.

You can start with `microk8s kubectl edit -n metallb-system ipaddresspool default-addresspool`

**Comment by sylnsr** [comment]
I found this doc helpful: https://microk8s.io/docs/addon-metallb#configure-ipaddresspool-resources-from-125

So basically just set a yaml file with whatever range you want, then apply it. For example, lets say you have a file named `addresspool.yaml` that now contains this:

```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec: 
  addresses:
  - 192.168.1.5-192.168.1.10
```

Apply it with `kubectl` as follows:  
`microk8s kubectl apply -f addresspool.yaml`
