### ISSUE TITLE
Set up Konnectivity service on microk8s

### ISSUE THREAD

**Issue by lloiacono-fuji** [canonical/microk8s#4897]
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

I'm trying to setup konnectivity on microk8s.
Can someone tell me if konnectivity is compatible?

According to the kubernetes guide, in point 4, it requires you to make changes to kube-apiserver on volumeMounts:

4. If you use UDS connection, add volumes config to the kube-apiserver:
```
spec:
  containers:
    volumeMounts:
    - name: konnectivity-uds
      mountPath: /etc/kubernetes/konnectivity-server
      readOnly: false
  volumes:
  - name: konnectivity-uds
    hostPath:
      path: /etc/kubernetes/konnectivity-server
      type: DirectoryOrCreate
```

Does anyone know if this setup is compatible with microk8s?

Thanks in advance!

**Comment by eaudetcobello** [comment]
Hi @lazzarello,

You can add the `--egress-selector-config-file` to /var/snap/microk8s/current/args/kube-apiserver and restart microk8s.

**Comment by lloiacono-fuji** [comment]
Hi @eaudetcobello ,
the --egress-selector-config-file to /var/snap/microk8s/current/args/kube-apiserver satisfies point 3

After, point 4 says to configure volumes on apiserver

4. If you use UDS connection, add volumes config to the kube-apiserver:
```
spec:
  containers:
    volumeMounts:
    - name: konnectivity-uds
      mountPath: /etc/kubernetes/konnectivity-server
      readOnly: false
  volumes:
  - name: konnectivity-uds
    hostPath:
      path: /etc/kubernetes/konnectivity-server
      type: DirectoryOrCreate
```

Do we need to bypass some point in the documentation?
Do you have documentation for setting up microk8s with konnectivity?
