### ISSUE TITLE
No datastore master nodes but cluster is still working

### ISSUE THREAD

**Issue by jnugh** [canonical/microk8s#5000]
#### Summary
We are running a multi node microk8s cluster with three datastore nodes and multiple worker nodes. Yesterday I noticed that microk8s status reports no datastore nodes (neither master nor standby nodes). We don't know when and how it started. We also don't understand why the cluster is still working and if the data available to each kubelite api server is consistent.

 I checked the code which generates the output and it makes the following call:
```sh
# /snap/microk8s/current/bin/dqlite  -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml  -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key  -f json k8s .cluster
Error: no available dqlite leader server found
```

`/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml` contains the following data
```yml
- ID: 3297041220608546238
  Address: 10.5.0.4:19001
  Role: 2
- ID: 10360074122386368580
  Address: 10.5.0.5:19001
  Role: 2
- ID: 442776466333799327
  Address: 10.5.0.10:19001
  Role: 2
- ID: 6363631146440140535
  Address: 10.5.0.11:19001
  Role: 2
- ID: 6048809877879767952
  Address: 10.10.5.11:19001
  Role: 0
- ID: 2169217021260995856
  Address: 10.10.5.12:19001
  Role: 0
- ID: 11804631294055090830
  Address: 10.10.5.13:19001
  Role: 0
```

The first four entries are no longer valid as we migrated the cluster last year. After the migration `microk8s status` had the new nodes as datastore nodes and everything was looking fine.

The docs at https://microk8s.io/docs/restore-quorum don't seem to apply to this. Reconfigure returns an error code 1 without additional details.

#### What Should Happen Instead?
This should obviously not happen. All three dqlite instances are up and running. Apart from a few server reboots they have always been available.

I'm not quite sure how severe this desync is. If the dqlite instances are out of sync now the kubernetes API should probably prevent writes to the datastore. 

#### Reproduction Steps
I don't know what triggered this issue.

#### Introspection Report
[inspection-report-20250402_072540.tar.gz](https://github.com/user-attachments/files/19563589/inspection-report-20250402_072540.tar.gz)

#### Can you suggest a fix?
-

#### Are you interested in contributing with a fix?
Sure if I can - however I have no idea how to identify the underlying issue.
