### ISSUE TITLE
Exposing Nginx-ingress to external traffic

### ISSUE THREAD

**Issue by moredhel** [canonical/microk8s#824]
I am wanting to expose my traffic to the internet,

When I enable ingress and define an ingress route, I have two services running which pick up on it:

- external-dns
- cert-manager

due to the way Nginx-ingress is configured, it does not pick up on the public ip of the running host, but instead defaults to `127.0.0.1`.

It would be useful to enable this as an option to allow serving traffic & automatically registering dns.

in order to do this, I copied the Nginx-ingress-controller yaml file in this repo, and updated the `--publish-status-address` to the public ip of my node.

I have found no documentation on this procedure, so was curious about whether or not this was a knob that had been intentionally hidden, and if so what the motivation behind it was.

Thanks

**Comment by ktsakalozos** [comment]
@moredhel thank you for reporting this. I think it is worth at least document your approach. Could you offer a self contained example on exactly what you are doing? Something that I can reproduce? Could you share the yaml manifests you are applying, eg the rules and a demo service? Thank you.

**Comment by moredhel** [comment]
@ktsakalozos sure thing,

I ended up cloning the microk8s repo & making the change there. The following can be run from the root directory of master:

```
sed -i 's/127.0.0.1/$(curl -4 ifconfig.io)/' microk8s-resources/actions/enable.ingress.sh
```

Then, to test:

1. enable ingress
2. install & configure external-dns
```
        helm upgrade \
                --version=2.10.2 \
                --namespace=kube-system \
                -i external-dns \
                -f values.yaml \
                stable/external-dns
```

sample _values.yaml_:
```
image:
  repository: bitnami/external-dns
  tag: 0.5.17-debian-9-r25

## The DNS provider where the DNS records will be created (options: aws, google, inmemory, azure )
provider: cloudflare

## This controls which types of resource external-dns should 'watch' for new
## DNS entries.
sources:
  - ingress

## RBAC parameteres
## https://kubernetes.io/docs/reference/access-authn-authz/rbac/
##
rbac:
  create: true


resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m

cloudflare:
  proxied: false
  apiToken: "<><><><>"
  email: "cloudflare@example.com"

## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
policy: upsert-only

## Prometheus Exporter / Metrics
##
metrics:
  enabled: true
```
2. create an ingress resource (doesn't matter what) (eg. mydomain.example.com)


## Expected output
```
dig +short @8.8.8.8 mydomain.example.com
> $(curl -4 ifconfig.io)
```

## Actual
```
dig +short @8.8.8.8 mydomain.example.com
> 127.0.0.1
```

Looking at the shell script, one fix could be allowing an override of the ip address to something user-configurable (similar perhaps to how istio enable works, with a default of 127.0.0.1)

If you're happy with that, I can submit a PR.

& If you need any more information, let me know.

Thanks
